"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Comprehensive test suite for the world-builder-site application
"""
import pytest
from fastapi.testclient import TestClient
from sqlmodel import Session, create_engine, SQLModel
from typing import Generator
import tempfile
import os

from src.app.main import app
from src.database import get_db
from src.models.user import User, UserCreate
from src.models.session import GameSession, SessionCreate
from src.models.timeline import TimelineEvent
from src.models.tile import Tile
from src.models.entity import Entity
from src.engine.card_engine import CardEngine, Card, Deck
from src.engine.rules_loader import RulesLoader

# Test database setup
@pytest.fixture(scope="session")
def test_engine():
    """Create test database engine"""
    engine = create_engine("sqlite:///:memory:", echo=False)
    SQLModel.metadata.create_all(engine)
    return engine

@pytest.fixture(scope="function")
def test_session(test_engine):
    """Create test database session"""
    with Session(test_engine) as session:
        yield session

@pytest.fixture(scope="function")
def client(test_session):
    """Create test client with database override"""
    def get_test_db():
        yield test_session
    
    app.dependency_overrides[get_db] = get_test_db
    with TestClient(app) as test_client:
        yield test_client
    app.dependency_overrides.clear()

# Test data fixtures
@pytest.fixture
def sample_user_data():
    """Sample user data for testing"""
    return {
        "username": "testuser",
        "email": "test@example.com",
        "password": "testpassword123"
    }

@pytest.fixture
def sample_session_data():
    """Sample session data for testing"""
    return {
        "name": "Test Session",
        "description": "A test world-building session",
        "current_stage": "foundation"
    }

@pytest.fixture
def sample_timeline_data():
    """Sample timeline data for testing"""
    return {
        "move_id": 1,
        "year": 100,
        "description": "Test event",
        "card_id": "test_card",
        "event_type": "card_draw"
    }

@pytest.fixture
def sample_tile_data():
    """Sample tile data for testing"""
    return {
        "x": 5,
        "y": 5,
        "tile_type": "land",
        "notes": "Test tile"
    }

@pytest.fixture
def sample_entity_data():
    """Sample entity data for testing"""
    return {
        "name": "Test City",
        "entity_type": "city",
        "x": 5,
        "y": 5,
        "description": "A test city",
        "size": 2
    }

# Model tests
class TestUser:
    """Test User model"""
    
    def test_user_creation(self, test_session, sample_user_data):
        """Test user creation"""
        user = User(
            username=sample_user_data["username"],
            email=sample_user_data["email"],
            hashed_password="hashed_password"
        )
        
        test_session.add(user)
        test_session.commit()
        test_session.refresh(user)
        
        assert user.id is not None
        assert user.username == sample_user_data["username"]
        assert user.email == sample_user_data["email"]
        assert user.is_active is True
    
    def test_user_unique_constraints(self, test_session, sample_user_data):
        """Test user unique constraints"""
        # Create first user
        user1 = User(
            username=sample_user_data["username"],
            email=sample_user_data["email"],
            hashed_password="hashed_password"
        )
        test_session.add(user1)
        test_session.commit()
        
        # Try to create duplicate username
        user2 = User(
            username=sample_user_data["username"],
            email="different@example.com",
            hashed_password="hashed_password"
        )
        test_session.add(user2)
        
        with pytest.raises(Exception):  # Should raise integrity error
            test_session.commit()

class TestGameSession:
    """Test GameSession model"""
    
    def test_session_creation(self, test_session, sample_session_data):
        """Test session creation"""
        session = GameSession(
            name=sample_session_data["name"],
            description=sample_session_data["description"],
            current_stage=sample_session_data["current_stage"]
        )
        
        test_session.add(session)
        test_session.commit()
        test_session.refresh(session)
        
        assert session.id is not None
        assert session.name == sample_session_data["name"]
        assert session.description == sample_session_data["description"]
        assert session.current_stage == sample_session_data["current_stage"]
        assert session.move_count == 0
        assert session.current_year == 0

class TestCardEngine:
    """Test CardEngine functionality"""
    
    def test_card_creation(self):
        """Test card creation"""
        card = Card("test_card", "Test Card", "A test card", 0.5)
        
        assert card.id == "test_card"
        assert card.name == "Test Card"
        assert card.description == "A test card"
        assert card.probability == 0.5
    
    def test_deck_creation(self):
        """Test deck creation"""
        cards = [
            Card("card1", "Card 1", "First card", 0.3),
            Card("card2", "Card 2", "Second card", 0.7)
        ]
        deck = Deck("test_deck", cards)
        
        assert deck.name == "test_deck"
        assert len(deck.cards) == 2
        assert len(deck.drawn_cards) == 0
    
    def test_card_drawing(self):
        """Test card drawing"""
        cards = [
            Card("card1", "Card 1", "First card", 0.3),
            Card("card2", "Card 2", "Second card", 0.7)
        ]
        deck = Deck("test_deck", cards)
        
        drawn_card = deck.draw_card()
        
        assert drawn_card is not None
        assert len(deck.cards) == 1
        assert len(deck.drawn_cards) == 1
        assert drawn_card in deck.drawn_cards
    
    def test_card_engine_simulation(self):
        """Test card engine simulation"""
        engine = CardEngine()
        
        result = engine.simulate_move("foundation")
        
        assert result["success"] is True
        assert "card" in result
        assert "move_id" in result
        assert "year" in result
        assert "event" in result
        assert result["move_id"] == 1
        assert result["year"] > 0

class TestRulesLoader:
    """Test RulesLoader functionality"""
    
    def test_rules_loader_creation(self):
        """Test rules loader creation"""
        loader = RulesLoader()
        
        assert loader.is_loaded() is False
        assert loader.rules_version is None
    
    def test_default_rules_creation(self):
        """Test default rules creation"""
        loader = RulesLoader()
        loader._create_default_rules()
        
        assert loader.is_loaded() is True
        assert loader.rules_version == "2025-01-27"
        assert loader.rules_data is not None
        assert "stages" in loader.rules_data
    
    def test_rules_validation(self):
        """Test rules validation"""
        loader = RulesLoader()
        loader._create_default_rules()
        
        assert loader.validate_rules() is True

# API tests
class TestAPI:
    """Test API endpoints"""
    
    def test_root_endpoint(self, client):
        """Test root endpoint"""
        response = client.get("/")
        
        assert response.status_code == 200
        data = response.json()
        assert data["message"] == "World Builder Site API"
        assert data["version"] == "0.1.0"
        assert "endpoints" in data
    
    def test_health_endpoint(self, client):
        """Test health endpoint"""
        response = client.get("/health")
        
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "healthy"
        assert "database" in data
        assert "rules_loaded" in data
    
    def test_info_endpoint(self, client):
        """Test info endpoint"""
        response = client.get("/info")
        
        assert response.status_code == 200
        data = response.json()
        assert data["name"] == "World Builder Site API"
        assert "features" in data
        assert "game_engine" in data
    
    def test_sessions_list_empty(self, client):
        """Test sessions list when empty"""
        response = client.get("/sessions/")
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        assert len(data) == 0
    
    def test_create_session(self, client, sample_session_data):
        """Test session creation"""
        response = client.post("/sessions/", json=sample_session_data)
        
        assert response.status_code == 200
        data = response.json()
        assert data["name"] == sample_session_data["name"]
        assert data["description"] == sample_session_data["description"]
        assert data["current_stage"] == sample_session_data["current_stage"]
        assert "id" in data
    
    def test_simulate_anonymous(self, client):
        """Test anonymous simulation"""
        response = client.post("/simulate/anonymous", json={
            "session_id": "00000000-0000-0000-0000-000000000000",
            "moves": 3
        })
        
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        assert len(data["moves"]) == 3
        assert "final_year" in data
    
    def test_get_game_rules(self, client):
        """Test getting game rules"""
        response = client.get("/simulate/rules")
        
        assert response.status_code == 200
        data = response.json()
        assert "version" in data
        assert "stages" in data
        assert "session_state" in data

# Integration tests
class TestIntegration:
    """Integration tests"""
    
    def test_full_session_workflow(self, client, sample_session_data):
        """Test complete session workflow"""
        # Create session
        create_response = client.post("/sessions/", json=sample_session_data)
        assert create_response.status_code == 200
        session_data = create_response.json()
        session_id = session_data["id"]
        
        # Get session
        get_response = client.get(f"/sessions/{session_id}")
        assert get_response.status_code == 200
        
        # Get map state
        map_response = client.get(f"/map/{session_id}/state")
        assert map_response.status_code == 200
        
        # Export session
        export_response = client.get(f"/export/{session_id}")
        assert export_response.status_code == 200
    
    def test_error_handling(self, client):
        """Test error handling"""
        # Test 404 for non-existent session
        response = client.get("/sessions/00000000-0000-0000-0000-000000000000")
        assert response.status_code == 404
        
        # Test invalid data
        response = client.post("/sessions/", json={"invalid": "data"})
        assert response.status_code == 422

# Performance tests
class TestPerformance:
    """Performance tests"""
    
    def test_multiple_simulations(self, client):
        """Test multiple simulations performance"""
        import time
        
        start_time = time.time()
        
        for _ in range(10):
            response = client.post("/simulate/anonymous", json={
                "session_id": "00000000-0000-0000-0000-000000000000",
                "moves": 5
            })
            assert response.status_code == 200
        
        end_time = time.time()
        duration = end_time - start_time
        
        # Should complete 10 simulations in under 5 seconds
        assert duration < 5.0
    
    def test_concurrent_requests(self, client):
        """Test concurrent request handling"""
        import threading
        import time
        
        results = []
        
        def make_request():
            response = client.get("/health")
            results.append(response.status_code)
        
        threads = []
        for _ in range(5):
            thread = threading.Thread(target=make_request)
            threads.append(thread)
            thread.start()
        
        for thread in threads:
            thread.join()
        
        # All requests should succeed
        assert all(status == 200 for status in results)
        assert len(results) == 5

