"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Card engine for game mechanics and simulation
"""
import random
from typing import Dict, List, Optional, Any
from datetime import datetime
import json
from pathlib import Path

class Card:
    """Represents a game card"""
    def __init__(self, card_id: str, name: str, description: str, probability: float = 0.1):
        self.id = card_id
        self.name = name
        self.description = description
        self.probability = probability
        self.effects: List[str] = []
        self.stage: str = "foundation"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert card to dictionary"""
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "probability": self.probability,
            "effects": self.effects,
            "stage": self.stage
        }

class Deck:
    """Represents a deck of cards"""
    def __init__(self, name: str, cards: List[Card]):
        self.name = name
        self.cards = cards
        self.drawn_cards: List[Card] = []
    
    def draw_card(self) -> Optional[Card]:
        """Draw a random card from the deck"""
        if not self.cards:
            return None
        
        # Weighted random selection based on probability
        weights = [card.probability for card in self.cards]
        selected_card = random.choices(self.cards, weights=weights)[0]
        
        # Move card from deck to drawn cards
        self.cards.remove(selected_card)
        self.drawn_cards.append(selected_card)
        
        return selected_card
    
    def reset_deck(self):
        """Reset deck by moving all drawn cards back"""
        self.cards.extend(self.drawn_cards)
        self.drawn_cards.clear()
    
    def get_remaining_cards(self) -> List[Card]:
        """Get list of remaining cards"""
        return self.cards.copy()
    
    def get_drawn_cards(self) -> List[Card]:
        """Get list of drawn cards"""
        return self.drawn_cards.copy()

class CardEngine:
    """Main card engine for game mechanics"""
    
    def __init__(self):
        self.decks: Dict[str, Deck] = {}
        self.rules_version: str = "2025-01-27"
        self.current_stage: str = "foundation"
        self.move_count: int = 0
        self.current_year: int = 0
        
        # Initialize with default cards
        self._create_default_cards()
    
    def _create_default_cards(self):
        """Create default card set for testing"""
        foundation_cards = [
            Card("land_formation", "Land Formation", "The world's geography begins to take shape", 0.3),
            Card("water_source", "Water Source", "Rivers, lakes, and seas emerge", 0.2),
            Card("climate", "Climate Patterns", "Weather systems establish themselves", 0.2),
            Card("resources", "Natural Resources", "Minerals and materials become available", 0.2),
            Card("catastrophe", "Natural Disaster", "A major event reshapes the landscape", 0.1)
        ]
        
        civilization_cards = [
            Card("first_settlement", "First Settlement", "Humans establish their first permanent home", 0.3),
            Card("agriculture", "Agriculture", "Farming techniques are discovered", 0.25),
            Card("trade_routes", "Trade Routes", "Commerce begins between settlements", 0.2),
            Card("technology", "Technological Advancement", "New tools and techniques emerge", 0.15),
            Card("conflict", "Conflict", "Disputes arise between groups", 0.1)
        ]
        
        self.decks["foundation"] = Deck("Foundation", foundation_cards)
        self.decks["civilization"] = Deck("Civilization", civilization_cards)
    
    def draw_card(self, stage: Optional[str] = None) -> Optional[Card]:
        """Draw a card from the specified stage"""
        stage = stage or self.current_stage
        
        if stage not in self.decks:
            return None
        
        return self.decks[stage].draw_card()
    
    def simulate_move(self, stage: Optional[str] = None) -> Dict[str, Any]:
        """Simulate a complete move"""
        stage = stage or self.current_stage
        
        # Draw a card
        card = self.draw_card(stage)
        if not card:
            return {
                "success": False,
                "error": f"No cards available in stage: {stage}"
            }
        
        # Calculate year progression
        year_increment = random.randint(10, 50)  # Random year progression
        self.current_year += year_increment
        self.move_count += 1
        
        # Generate event description
        event_description = self._generate_event_description(card)
        
        return {
            "success": True,
            "card": card.to_dict(),
            "move_id": self.move_count,
            "year": self.current_year,
            "event": {
                "description": event_description,
                "effects": card.effects,
                "stage": stage
            }
        }
    
    def _generate_event_description(self, card: Card) -> str:
        """Generate a detailed event description"""
        base_description = card.description
        
        # Add contextual details based on current state
        if self.move_count == 1:
            return f"In the beginning, {base_description.lower()}"
        elif self.move_count <= 5:
            return f"Early in the world's history, {base_description.lower()}"
        else:
            return f"As time progresses, {base_description.lower()}"
    
    def reset_session(self):
        """Reset the current session"""
        self.move_count = 0
        self.current_year = 0
        self.current_stage = "foundation"
        
        # Reset all decks
        for deck in self.decks.values():
            deck.reset_deck()
    
    def get_session_state(self) -> Dict[str, Any]:
        """Get current session state"""
        return {
            "current_stage": self.current_stage,
            "move_count": self.move_count,
            "current_year": self.current_year,
            "rules_version": self.rules_version,
            "decks": {
                name: {
                    "remaining_cards": len(deck.cards),
                    "drawn_cards": len(deck.drawn_cards)
                }
                for name, deck in self.decks.items()
            }
        }
    
    def load_rules_from_file(self, file_path: str) -> bool:
        """Load game rules from JSON file"""
        try:
            rules_path = Path(file_path)
            if not rules_path.exists():
                return False
            
            with open(rules_path, 'r') as f:
                rules_data = json.load(f)
            
            # Parse rules and create decks
            self._parse_rules_data(rules_data)
            return True
            
        except Exception as e:
            print(f"Error loading rules: {e}")
            return False
    
    def _parse_rules_data(self, rules_data: Dict[str, Any]):
        """Parse rules data and create decks"""
        self.rules_version = rules_data.get("version", "2025-01-27")
        
        stages = rules_data.get("stages", [])
        for stage_data in stages:
            stage_name = stage_data.get("id", "unknown")
            cards_data = stage_data.get("cards", [])
            
            cards = []
            for card_data in cards_data:
                card = Card(
                    card_id=card_data.get("id", ""),
                    name=card_data.get("name", ""),
                    description=card_data.get("description", ""),
                    probability=card_data.get("probability", 0.1)
                )
                cards.append(card)
            
            self.decks[stage_name] = Deck(stage_name, cards)
    
    def export_rules(self) -> Dict[str, Any]:
        """Export current rules to dictionary"""
        return {
            "version": self.rules_version,
            "stages": [
                {
                    "id": name,
                    "name": deck.name,
                    "cards": [card.to_dict() for card in deck.cards + deck.drawn_cards]
                }
                for name, deck in self.decks.items()
            ]
        }

