"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Rules loader for game mechanics and card definitions
"""
import json
from pathlib import Path
from typing import Dict, Any, Optional
import os

class RulesLoader:
    """Loads and manages game rules from JSON files"""
    
    def __init__(self):
        self.rules_data: Optional[Dict[str, Any]] = None
        self.rules_version: Optional[str] = None
        self.rules_path: Optional[Path] = None
        self.is_loaded_flag: bool = False
    
    def load_rules(self, file_path: Optional[str] = None) -> bool:
        """Load rules from file"""
        if file_path is None:
            # Try to find rules file in project
            possible_paths = [
                "rules_v2025-01-27.json",
                "docs/rules_v2025-01-27.json",
                "src/rules_v2025-01-27.json"
            ]
            
            for path in possible_paths:
                if Path(path).exists():
                    file_path = path
                    break
            
            if file_path is None:
                # Create default rules if none exist
                self._create_default_rules()
                return True
        
        try:
            rules_path = Path(file_path)
            if not rules_path.exists():
                print(f"Rules file not found: {file_path}")
                return False
            
            with open(rules_path, 'r', encoding='utf-8') as f:
                self.rules_data = json.load(f)
            
            self.rules_version = self.rules_data.get("version", "unknown")
            self.rules_path = rules_path
            self.is_loaded_flag = True
            
            print(f"✅ Rules loaded from {file_path} (version: {self.rules_version})")
            return True
            
        except Exception as e:
            print(f"❌ Error loading rules from {file_path}: {e}")
            return False
    
    def _create_default_rules(self):
        """Create default rules if no file exists"""
        self.rules_data = {
            "version": "2025-01-27",
            "description": "Default world-building rules",
            "stages": [
                {
                    "id": "foundation",
                    "name": "Foundation",
                    "description": "Initial world building phase",
                    "cards": [
                        {
                            "id": "land_formation",
                            "name": "Land Formation",
                            "description": "The world's geography begins to take shape",
                            "probability": 0.3,
                            "effects": ["Creates landmasses", "Establishes terrain"]
                        },
                        {
                            "id": "water_source",
                            "name": "Water Source",
                            "description": "Rivers, lakes, and seas emerge",
                            "probability": 0.25,
                            "effects": ["Creates water bodies", "Establishes water cycle"]
                        },
                        {
                            "id": "climate",
                            "name": "Climate Patterns",
                            "description": "Weather systems establish themselves",
                            "probability": 0.2,
                            "effects": ["Creates weather patterns", "Establishes seasons"]
                        },
                        {
                            "id": "resources",
                            "name": "Natural Resources",
                            "description": "Minerals and materials become available",
                            "probability": 0.2,
                            "effects": ["Creates mineral deposits", "Enables crafting"]
                        },
                        {
                            "id": "catastrophe",
                            "name": "Natural Disaster",
                            "description": "A major event reshapes the landscape",
                            "probability": 0.05,
                            "effects": ["Changes terrain", "Creates new opportunities"]
                        }
                    ]
                },
                {
                    "id": "civilization",
                    "name": "Civilization",
                    "description": "Human settlement and development",
                    "cards": [
                        {
                            "id": "first_settlement",
                            "name": "First Settlement",
                            "description": "Humans establish their first permanent home",
                            "probability": 0.3,
                            "effects": ["Creates first city", "Enables population growth"]
                        },
                        {
                            "id": "agriculture",
                            "name": "Agriculture",
                            "description": "Farming techniques are discovered",
                            "probability": 0.25,
                            "effects": ["Enables food production", "Supports larger populations"]
                        },
                        {
                            "id": "trade_routes",
                            "name": "Trade Routes",
                            "description": "Commerce begins between settlements",
                            "probability": 0.2,
                            "effects": ["Enables resource exchange", "Connects settlements"]
                        },
                        {
                            "id": "technology",
                            "name": "Technological Advancement",
                            "description": "New tools and techniques emerge",
                            "probability": 0.15,
                            "effects": ["Improves efficiency", "Enables new capabilities"]
                        },
                        {
                            "id": "conflict",
                            "name": "Conflict",
                            "description": "Disputes arise between groups",
                            "probability": 0.1,
                            "effects": ["Creates tension", "May lead to war or peace"]
                        }
                    ]
                }
            ]
        }
        
        self.rules_version = self.rules_data["version"]
        self.is_loaded_flag = True
        
        # Save default rules to file
        self.save_rules("rules_v2025-01-27.json")
        print("✅ Default rules created and saved")
    
    def save_rules(self, file_path: str) -> bool:
        """Save current rules to file"""
        if not self.rules_data:
            print("❌ No rules data to save")
            return False
        
        try:
            rules_path = Path(file_path)
            with open(rules_path, 'w', encoding='utf-8') as f:
                json.dump(self.rules_data, f, indent=2, ensure_ascii=False)
            
            print(f"✅ Rules saved to {file_path}")
            return True
            
        except Exception as e:
            print(f"❌ Error saving rules to {file_path}: {e}")
            return False
    
    def get_rules(self) -> Optional[Dict[str, Any]]:
        """Get current rules data"""
        return self.rules_data
    
    def get_stage(self, stage_id: str) -> Optional[Dict[str, Any]]:
        """Get specific stage rules"""
        if not self.rules_data or "stages" not in self.rules_data:
            return None
        
        for stage in self.rules_data["stages"]:
            if stage.get("id") == stage_id:
                return stage
        
        return None
    
    def get_card(self, stage_id: str, card_id: str) -> Optional[Dict[str, Any]]:
        """Get specific card from stage"""
        stage = self.get_stage(stage_id)
        if not stage or "cards" not in stage:
            return None
        
        for card in stage["cards"]:
            if card.get("id") == card_id:
                return card
        
        return None
    
    def is_loaded(self) -> bool:
        """Check if rules are loaded"""
        return self.is_loaded_flag
    
    def get_version(self) -> Optional[str]:
        """Get rules version"""
        return self.rules_version
    
    def validate_rules(self) -> bool:
        """Validate current rules structure"""
        if not self.rules_data:
            return False
        
        required_fields = ["version", "stages"]
        for field in required_fields:
            if field not in self.rules_data:
                print(f"❌ Missing required field: {field}")
                return False
        
        # Validate stages
        stages = self.rules_data["stages"]
        if not isinstance(stages, list) or len(stages) == 0:
            print("❌ Stages must be a non-empty list")
            return False
        
        for stage in stages:
            if not self._validate_stage(stage):
                return False
        
        print("✅ Rules validation passed")
        return True
    
    def _validate_stage(self, stage: Dict[str, Any]) -> bool:
        """Validate individual stage"""
        required_fields = ["id", "name", "cards"]
        for field in required_fields:
            if field not in stage:
                print(f"❌ Stage missing required field: {field}")
                return False
        
        # Validate cards
        cards = stage["cards"]
        if not isinstance(cards, list):
            print(f"❌ Stage {stage['id']} cards must be a list")
            return False
        
        for card in cards:
            if not self._validate_card(card):
                return False
        
        return True
    
    def _validate_card(self, card: Dict[str, Any]) -> bool:
        """Validate individual card"""
        required_fields = ["id", "name", "description", "probability"]
        for field in required_fields:
            if field not in card:
                print(f"❌ Card missing required field: {field}")
                return False
        
        # Validate probability
        probability = card["probability"]
        if not isinstance(probability, (int, float)) or not (0 <= probability <= 1):
            print(f"❌ Card {card['id']} probability must be between 0 and 1")
            return False
        
        return True

