"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-10-15
Purpose: Core FastAPI application with essential endpoints and Vercel support
"""
from fastapi import FastAPI, HTTPException, Depends, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from contextlib import asynccontextmanager
from typing import Optional
import uvicorn
import time
from sqlmodel import Session

from src.config import load_config
from src.database import init_db, get_async_session
from src.models.user import User
from src.engine.card_engine import CardEngine
from src.engine.rules_loader import RulesLoader
from src.api.auth import router as auth_router
from src.api.sessions import router as sessions_router
from src.api.simulate import router as simulate_router
from src.api.map import router as map_router
from src.api.export import router as export_router

# Load configuration
config = load_config()

# Security
security = HTTPBearer()

# Game engine
card_engine = CardEngine()
rules_loader = RulesLoader()

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan manager"""
    # Startup
    print(f"Starting World Builder Site API ({config.environment})...")
    
    # Create database tables
    if config.environment != "production":  # Don't auto-migrate in production
        init_db()
        print("Database tables created")
    
    # Load game rules
    try:
        rules_loader.load_rules()
        print("Game rules loaded")
    except Exception as e:
        print(f"Warning: Could not load game rules: {e}")
    
    yield
    
    # Shutdown
    print("Shutting down World Builder Site API...")

# Create FastAPI app
app = FastAPI(
    title=config.api.title,
    description="Backend API for collaborative world-building application",
    version=config.api.version,
    docs_url=config.api.docs_url,
    redoc_url=config.api.redoc_url,
    lifespan=lifespan
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=config.api.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Database dependency
async def get_db():
    """Get database session"""
    async with get_async_session() as session:
        yield session

# Authentication dependency
async def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security),
    db: Session = Depends(get_db)
) -> Optional[User]:
    """Get current authenticated user"""
    # TODO: Implement JWT token validation
    # For now, return None (anonymous access)
    return None

# Include routers
app.include_router(auth_router, prefix="/auth", tags=["Authentication"])
app.include_router(sessions_router, prefix="/sessions", tags=["Sessions"])
app.include_router(simulate_router, prefix="/simulate", tags=["Simulation"])
app.include_router(map_router, prefix="/map", tags=["Map"])
app.include_router(export_router, prefix="/export", tags=["Export"])

@app.get("/")
async def root():
    """Root endpoint"""
    return {
        "message": config.api.title,
        "version": config.api.version,
        "environment": config.environment,
        "status": "running",
        "endpoints": {
            "docs": config.api.docs_url,
            "health": "/health",
            "auth": "/auth",
            "sessions": "/sessions",
            "simulate": "/simulate",
            "map": "/map",
            "export": "/export"
        }
    }

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    try:
        # Test database connection
        async with get_async_session() as session:
            result = session.exec("SELECT 1")
            result.all()  # Actually execute the query
        
        return {
            "status": "healthy",
            "environment": config.environment,
            "database": "connected",
            "rules_loaded": rules_loader.is_loaded(),
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Service unhealthy: {str(e)}"
        )

@app.get("/info")
async def api_info():
    """API information endpoint"""
    return {
        "name": "World Builder Site API",
        "version": "0.1.0",
        "description": "Backend API for collaborative world-building application",
        "features": [
            "User authentication",
            "Session management", 
            "Card-based simulation",
            "Timeline management",
            "Interactive map",
            "Export/import functionality"
        ],
        "game_engine": {
            "card_engine": "active",
            "rules_loader": "active" if rules_loader.is_loaded() else "inactive"
        }
    }

if __name__ == "__main__":
    uvicorn.run(
        "src.app.main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        log_level="info"
    )