"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Core FastAPI application with essential endpoints
"""
from fastapi import FastAPI, HTTPException, Depends, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from sqlmodel import SQLModel, create_engine, Session
from contextlib import asynccontextmanager
import os
from typing import Optional, List
import uvicorn

from src.models.user import User, UserCreate, UserResponse
from src.models.session import GameSession, SessionCreate, SessionResponse
from src.models.timeline import TimelineEvent, TimelineEventCreate, TimelineEventResponse
from src.models.tile import Tile, TileCreate, TileResponse
from src.models.entity import Entity, EntityCreate, EntityResponse
from src.engine.card_engine import CardEngine
from src.engine.rules_loader import RulesLoader
from src.api.auth import router as auth_router
from src.api.sessions import router as sessions_router
from src.api.simulate import router as simulate_router
from src.api.map import router as map_router
from src.api.export import router as export_router

# Database setup
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./world_builder.db")
engine = create_engine(DATABASE_URL, echo=False)

# Security
security = HTTPBearer()

# Game engine
card_engine = CardEngine()
rules_loader = RulesLoader()

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan manager"""
    # Startup
    print("Starting World Builder Site API...")
    
    # Create database tables
    SQLModel.metadata.create_all(engine)
    print("Database tables created")
    
    # Load game rules
    try:
        rules_loader.load_rules()
        print("Game rules loaded")
    except Exception as e:
        print(f"Warning: Could not load game rules: {e}")
    
    yield
    
    # Shutdown
    print("Shutting down World Builder Site API...")

# Create FastAPI app
app = FastAPI(
    title="World Builder Site API",
    description="Backend API for collaborative world-building application",
    version="0.1.0",
    lifespan=lifespan
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:5173", "http://127.0.0.1:3000", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Database dependency
def get_db():
    """Get database session"""
    with Session(engine) as session:
        yield session

# Authentication dependency
async def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security),
    db: Session = Depends(get_db)
) -> Optional[User]:
    """Get current authenticated user"""
    # TODO: Implement JWT token validation
    # For now, return None (anonymous access)
    return None

# Include routers
app.include_router(auth_router, prefix="/auth", tags=["Authentication"])
app.include_router(sessions_router, prefix="/sessions", tags=["Sessions"])
app.include_router(simulate_router, prefix="/simulate", tags=["Simulation"])
app.include_router(map_router, prefix="/map", tags=["Map"])
app.include_router(export_router, prefix="/export", tags=["Export"])

@app.get("/")
async def root():
    """Root endpoint"""
    return {
        "message": "World Builder Site API",
        "version": "0.1.0",
        "status": "running",
        "endpoints": {
            "docs": "/docs",
            "health": "/health",
            "auth": "/auth",
            "sessions": "/sessions",
            "simulate": "/simulate",
            "map": "/map",
            "export": "/export"
        }
    }

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    try:
        # Test database connection
        with Session(engine) as session:
            session.exec("SELECT 1")
        
        return {
            "status": "healthy",
            "database": "connected",
            "rules_loaded": rules_loader.is_loaded(),
            "timestamp": "2025-01-27T00:00:00Z"
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Service unhealthy: {str(e)}"
        )

@app.get("/info")
async def api_info():
    """API information endpoint"""
    return {
        "name": "World Builder Site API",
        "version": "0.1.0",
        "description": "Backend API for collaborative world-building application",
        "features": [
            "User authentication",
            "Session management", 
            "Card-based simulation",
            "Timeline management",
            "Interactive map",
            "Export/import functionality"
        ],
        "game_engine": {
            "card_engine": "active",
            "rules_loader": "active" if rules_loader.is_loaded() else "inactive"
        }
    }

if __name__ == "__main__":
    uvicorn.run(
        "src.app.main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        log_level="info"
    )