"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Export/Import API endpoints
"""
from fastapi import APIRouter, HTTPException, Depends, status
from sqlmodel import Session, select
from typing import Optional
from uuid import UUID
from datetime import datetime
from pydantic import BaseModel

from src.models.session import GameSession, SessionState
from src.models.timeline import TimelineEvent
from src.models.tile import Tile
from src.models.entity import Entity
from src.models.user import User
from src.database import get_db
from src.api.auth import get_current_user

router = APIRouter()

class ExportResponse(BaseModel):
    """Response model for session export"""
    session: dict
    timeline: list
    map: dict
    exported_at: str

class ImportRequest(BaseModel):
    """Request model for session import"""
    session: dict
    timeline: list = []
    map: dict = {"tiles": [], "entities": []}

class ImportResponse(BaseModel):
    """Response model for session import"""
    id: UUID
    name: str
    imported_at: str

@router.get("/{session_id}", response_model=ExportResponse)
async def export_session(
    session_id: UUID,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Export session data"""
    # Get session
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    # Get timeline events
    timeline_query = select(TimelineEvent).where(TimelineEvent.session_id == session_id)
    timeline_events = db.exec(timeline_query).all()
    
    # Get tiles
    tiles_query = select(Tile).where(Tile.session_id == session_id)
    tiles = db.exec(tiles_query).all()
    
    # Get entities
    entities_query = select(Entity).where(Entity.session_id == session_id)
    entities = db.exec(entities_query).all()
    
    return ExportResponse(
        session={
            "id": str(session.id),
            "name": session.name,
            "description": session.description,
            "is_active": session.is_active,
            "current_stage": session.current_stage,
            "move_count": session.move_count,
            "current_year": session.current_year,
            "created_at": session.created_at.isoformat(),
            "updated_at": session.updated_at.isoformat() if session.updated_at else None
        },
        timeline=[
            {
                "id": str(event.id),
                "move_id": event.move_id,
                "year": event.year,
                "description": event.description,
                "card_id": event.card_id,
                "event_type": event.event_type,
                "created_at": event.created_at.isoformat()
            }
            for event in timeline_events
        ],
        map={
            "tiles": [
                {
                    "id": str(tile.id),
                    "x": tile.x,
                    "y": tile.y,
                    "tile_type": tile.tile_type,
                    "notes": tile.notes,
                    "created_at": tile.created_at.isoformat(),
                    "updated_at": tile.updated_at.isoformat() if tile.updated_at else None
                }
                for tile in tiles
            ],
            "entities": [
                {
                    "id": str(entity.id),
                    "name": entity.name,
                    "entity_type": entity.entity_type,
                    "x": entity.x,
                    "y": entity.y,
                    "description": entity.description,
                    "size": entity.size,
                    "created_at": entity.created_at.isoformat(),
                    "updated_at": entity.updated_at.isoformat() if entity.updated_at else None
                }
                for entity in entities
            ]
        },
        exported_at=datetime.utcnow().isoformat()
    )

@router.post("/import", response_model=ImportResponse)
async def import_session(
    import_data: ImportRequest,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Import session data"""
    try:
        # Create new session
        session_data = import_data.session
        session = GameSession(
            name=session_data.get("name", "Imported Session"),
            description=session_data.get("description"),
            current_stage=session_data.get("current_stage", "foundation"),
            move_count=session_data.get("move_count", 0),
            current_year=session_data.get("current_year", 0),
            user_id=current_user.id if current_user else None
        )
        
        db.add(session)
        db.commit()
        db.refresh(session)
        
        # Import timeline events
        for event_data in import_data.timeline:
            timeline_event = TimelineEvent(
                session_id=session.id,
                move_id=event_data.get("move_id", 1),
                year=event_data.get("year", 0),
                description=event_data.get("description", ""),
                card_id=event_data.get("card_id"),
                event_type=event_data.get("event_type", "card_draw")
            )
            db.add(timeline_event)
        
        # Import tiles
        map_data = import_data.map
        for tile_data in map_data.get("tiles", []):
            tile = Tile(
                session_id=session.id,
                x=tile_data.get("x", 0),
                y=tile_data.get("y", 0),
                tile_type=tile_data.get("tile_type", "empty"),
                notes=tile_data.get("notes")
            )
            db.add(tile)
        
        # Import entities
        for entity_data in map_data.get("entities", []):
            entity = Entity(
                session_id=session.id,
                name=entity_data.get("name", ""),
                entity_type=entity_data.get("entity_type", "landmark"),
                x=entity_data.get("x", 0),
                y=entity_data.get("y", 0),
                description=entity_data.get("description"),
                size=entity_data.get("size", 1)
            )
            db.add(entity)
        
        db.commit()
        
        return ImportResponse(
            id=session.id,
            name=session.name,
            imported_at=datetime.utcnow().isoformat()
        )
        
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Import failed: {str(e)}"
        )

@router.get("/{session_id}/timeline")
async def export_timeline(
    session_id: UUID,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Export session timeline only"""
    # Get session
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    # Get timeline events
    timeline_query = select(TimelineEvent).where(TimelineEvent.session_id == session_id)
    timeline_events = db.exec(timeline_query).all()
    
    return {
        "session_id": str(session_id),
        "events": [
            {
                "id": str(event.id),
                "move_id": event.move_id,
                "year": event.year,
                "description": event.description,
                "card_id": event.card_id,
                "event_type": event.event_type,
                "created_at": event.created_at.isoformat()
            }
            for event in timeline_events
        ],
        "exported_at": datetime.utcnow().isoformat()
    }

@router.get("/{session_id}/map")
async def export_map(
    session_id: UUID,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Export session map only"""
    # Get session
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    # Get tiles
    tiles_query = select(Tile).where(Tile.session_id == session_id)
    tiles = db.exec(tiles_query).all()
    
    # Get entities
    entities_query = select(Entity).where(Entity.session_id == session_id)
    entities = db.exec(entities_query).all()
    
    return {
        "session_id": str(session_id),
        "tiles": [
            {
                "id": str(tile.id),
                "x": tile.x,
                "y": tile.y,
                "tile_type": tile.tile_type,
                "notes": tile.notes,
                "created_at": tile.created_at.isoformat(),
                "updated_at": tile.updated_at.isoformat() if tile.updated_at else None
            }
            for tile in tiles
        ],
        "entities": [
            {
                "id": str(entity.id),
                "name": entity.name,
                "entity_type": entity.entity_type,
                "x": entity.x,
                "y": entity.y,
                "description": entity.description,
                "size": entity.size,
                "created_at": entity.created_at.isoformat(),
                "updated_at": entity.updated_at.isoformat() if entity.updated_at else None
            }
            for entity in entities
        ],
        "exported_at": datetime.utcnow().isoformat()
    }

