"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Map management API endpoints
"""
from fastapi import APIRouter, HTTPException, Depends, status
from sqlmodel import Session, select
from typing import List, Optional
from uuid import UUID
from datetime import datetime

from src.models.tile import Tile, TileCreate, TileResponse, TileUpdate, MapState
from src.models.entity import Entity, EntityCreate, EntityResponse, EntityUpdate
from src.models.session import GameSession
from src.models.user import User
from src.database import get_db
from src.api.auth import get_current_user

router = APIRouter()

@router.get("/{session_id}/state", response_model=MapState)
async def get_map_state(
    session_id: UUID,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get complete map state for a session"""
    # Get session
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    # Get tiles
    tiles_query = select(Tile).where(Tile.session_id == session_id)
    tiles = db.exec(tiles_query).all()
    
    # Get entities
    entities_query = select(Entity).where(Entity.session_id == session_id)
    entities = db.exec(entities_query).all()
    
    return MapState(
        tiles=[TileResponse.from_orm(tile) for tile in tiles],
        entities=[EntityResponse.from_orm(entity) for entity in entities],
        width=20,
        height=12
    )

@router.post("/{session_id}/tiles", response_model=TileResponse)
async def create_tile(
    session_id: UUID,
    tile_data: TileCreate,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Create or update a tile"""
    # Get session
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    # Check if tile already exists
    existing_tile = db.exec(
        select(Tile).where(
            Tile.session_id == session_id,
            Tile.x == tile_data.x,
            Tile.y == tile_data.y
        )
    ).first()
    
    if existing_tile:
        # Update existing tile
        existing_tile.tile_type = tile_data.tile_type
        existing_tile.notes = tile_data.notes
        existing_tile.updated_at = datetime.utcnow()
        
        db.add(existing_tile)
        db.commit()
        db.refresh(existing_tile)
        
        return TileResponse.from_orm(existing_tile)
    else:
        # Create new tile
        tile = Tile(
            session_id=session_id,
            x=tile_data.x,
            y=tile_data.y,
            tile_type=tile_data.tile_type,
            notes=tile_data.notes
        )
        
        db.add(tile)
        db.commit()
        db.refresh(tile)
        
        return TileResponse.from_orm(tile)

@router.put("/{session_id}/tiles/{tile_id}", response_model=TileResponse)
async def update_tile(
    session_id: UUID,
    tile_id: UUID,
    tile_data: TileUpdate,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Update a tile"""
    # Get tile
    tile = db.get(Tile, tile_id)
    if not tile or tile.session_id != session_id:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Tile not found"
        )
    
    # Get session for permission check
    session = db.get(GameSession, session_id)
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    # Update tile
    update_data = tile_data.dict(exclude_unset=True)
    for field, value in update_data.items():
        setattr(tile, field, value)
    
    tile.updated_at = datetime.utcnow()
    
    db.add(tile)
    db.commit()
    db.refresh(tile)
    
    return TileResponse.from_orm(tile)

@router.delete("/{session_id}/tiles/{tile_id}")
async def delete_tile(
    session_id: UUID,
    tile_id: UUID,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Delete a tile"""
    # Get tile
    tile = db.get(Tile, tile_id)
    if not tile or tile.session_id != session_id:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Tile not found"
        )
    
    # Get session for permission check
    session = db.get(GameSession, session_id)
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    db.delete(tile)
    db.commit()
    
    return {"message": "Tile deleted successfully"}

@router.post("/{session_id}/entities", response_model=EntityResponse)
async def create_entity(
    session_id: UUID,
    entity_data: EntityCreate,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Create an entity"""
    # Get session
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    # Create entity
    entity = Entity(
        session_id=session_id,
        name=entity_data.name,
        entity_type=entity_data.entity_type,
        x=entity_data.x,
        y=entity_data.y,
        description=entity_data.description,
        size=entity_data.size
    )
    
    db.add(entity)
    db.commit()
    db.refresh(entity)
    
    return EntityResponse.from_orm(entity)

@router.put("/{session_id}/entities/{entity_id}", response_model=EntityResponse)
async def update_entity(
    session_id: UUID,
    entity_id: UUID,
    entity_data: EntityUpdate,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Update an entity"""
    # Get entity
    entity = db.get(Entity, entity_id)
    if not entity or entity.session_id != session_id:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Entity not found"
        )
    
    # Get session for permission check
    session = db.get(GameSession, session_id)
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    # Update entity
    update_data = entity_data.dict(exclude_unset=True)
    for field, value in update_data.items():
        setattr(entity, field, value)
    
    entity.updated_at = datetime.utcnow()
    
    db.add(entity)
    db.commit()
    db.refresh(entity)
    
    return EntityResponse.from_orm(entity)

@router.delete("/{session_id}/entities/{entity_id}")
async def delete_entity(
    session_id: UUID,
    entity_id: UUID,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Delete an entity"""
    # Get entity
    entity = db.get(Entity, entity_id)
    if not entity or entity.session_id != session_id:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Entity not found"
        )
    
    # Get session for permission check
    session = db.get(GameSession, session_id)
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    db.delete(entity)
    db.commit()
    
    return {"message": "Entity deleted successfully"}

