"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Session management API endpoints
"""
from fastapi import APIRouter, HTTPException, Depends, status
from sqlmodel import Session, select
from typing import List, Optional
from uuid import UUID

from src.models.session import GameSession, SessionCreate, SessionResponse, SessionUpdate
from src.models.user import User
from src.database import get_db
from src.api.auth import get_current_user

router = APIRouter()

@router.get("/", response_model=List[SessionResponse])
async def list_sessions(
    skip: int = 0,
    limit: int = 100,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """List user sessions"""
    query = select(GameSession)
    
    # Filter by user if authenticated
    if current_user:
        query = query.where(GameSession.user_id == current_user.id)
    else:
        # For anonymous users, only show public sessions
        query = query.where(GameSession.user_id.is_(None))
    
    query = query.offset(skip).limit(limit)
    sessions = db.exec(query).all()
    
    return [SessionResponse.from_orm(session) for session in sessions]

@router.post("/", response_model=SessionResponse)
async def create_session(
    session_data: SessionCreate,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Create a new session"""
    session = GameSession(
        name=session_data.name,
        description=session_data.description,
        current_stage=session_data.current_stage,
        user_id=current_user.id if current_user else None
    )
    
    db.add(session)
    db.commit()
    db.refresh(session)
    
    return SessionResponse.from_orm(session)

@router.get("/{session_id}", response_model=SessionResponse)
async def get_session(
    session_id: UUID,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get session by ID"""
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    return SessionResponse.from_orm(session)

@router.put("/{session_id}", response_model=SessionResponse)
async def update_session(
    session_id: UUID,
    session_data: SessionUpdate,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Update session"""
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    # Update fields
    update_data = session_data.dict(exclude_unset=True)
    for field, value in update_data.items():
        setattr(session, field, value)
    
    session.updated_at = datetime.utcnow()
    
    db.add(session)
    db.commit()
    db.refresh(session)
    
    return SessionResponse.from_orm(session)

@router.delete("/{session_id}")
async def delete_session(
    session_id: UUID,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Delete session"""
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    db.delete(session)
    db.commit()
    
    return {"message": "Session deleted successfully"}

@router.get("/{session_id}/state")
async def get_session_state(
    session_id: UUID,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get complete session state"""
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    return {
        "session": SessionResponse.from_orm(session),
        "timeline": [],  # TODO: Load timeline events
        "map": {
            "tiles": [],  # TODO: Load tiles
            "entities": []  # TODO: Load entities
        }
    }

