"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Simulation API endpoints for card drawing and game mechanics
"""
from fastapi import APIRouter, HTTPException, Depends, status
from sqlmodel import Session
from typing import Optional
from uuid import UUID
from pydantic import BaseModel

from src.models.session import GameSession
from src.models.timeline import TimelineEvent, TimelineEventCreate
from src.models.user import User
from src.database import get_db
from src.api.auth import get_current_user
from src.engine.card_engine import CardEngine

router = APIRouter()

class DrawCardRequest(BaseModel):
    """Request model for drawing a card"""
    session_id: UUID
    stage: Optional[str] = None

class DrawCardResponse(BaseModel):
    """Response model for card draw"""
    success: bool
    card: Optional[dict] = None
    move_id: Optional[int] = None
    year: Optional[int] = None
    event: Optional[dict] = None
    error: Optional[str] = None

class SimulateRequest(BaseModel):
    """Request model for simulation"""
    session_id: UUID
    moves: int = 1
    stage: Optional[str] = None

class SimulateResponse(BaseModel):
    """Response model for simulation"""
    success: bool
    moves: list = []
    final_year: Optional[int] = None
    error: Optional[str] = None

# Initialize card engine
card_engine = CardEngine()

@router.post("/draw", response_model=DrawCardResponse)
async def draw_card(
    request: DrawCardRequest,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Draw a card for a session"""
    # Get session
    session = db.get(GameSession, request.session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    try:
        # Simulate move
        result = card_engine.simulate_move(request.stage or session.current_stage)
        
        if not result["success"]:
            return DrawCardResponse(
                success=False,
                error=result["error"]
            )
        
        # Create timeline event
        timeline_event = TimelineEvent(
            session_id=request.session_id,
            move_id=result["move_id"],
            year=result["year"],
            description=result["event"]["description"],
            card_id=result["card"]["id"],
            event_type="card_draw"
        )
        
        db.add(timeline_event)
        
        # Update session
        session.move_count = result["move_id"]
        session.current_year = result["year"]
        session.current_stage = result["event"]["stage"]
        
        db.add(session)
        db.commit()
        
        return DrawCardResponse(
            success=True,
            card=result["card"],
            move_id=result["move_id"],
            year=result["year"],
            event=result["event"]
        )
        
    except Exception as e:
        return DrawCardResponse(
            success=False,
            error=f"Simulation error: {str(e)}"
        )

@router.post("/anonymous", response_model=SimulateResponse)
async def simulate_anonymous(
    request: SimulateRequest
):
    """Run anonymous simulation without saving to database"""
    try:
        # Reset engine for anonymous simulation
        card_engine.reset_session()
        
        moves = []
        for i in range(request.moves):
            result = card_engine.simulate_move(request.stage)
            
            if not result["success"]:
                return SimulateResponse(
                    success=False,
                    error=result["error"]
                )
            
            moves.append({
                "move_id": result["move_id"],
                "year": result["year"],
                "description": result["event"]["description"],
                "card": result["card"]
            })
        
        return SimulateResponse(
            success=True,
            moves=moves,
            final_year=card_engine.current_year
        )
        
    except Exception as e:
        return SimulateResponse(
            success=False,
            error=f"Simulation error: {str(e)}"
        )

@router.get("/rules")
async def get_game_rules():
    """Get current game rules"""
    return {
        "version": card_engine.rules_version,
        "stages": list(card_engine.decks.keys()),
        "session_state": card_engine.get_session_state()
    }

@router.post("/reset")
async def reset_simulation(
    session_id: UUID,
    current_user: Optional[User] = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Reset simulation for a session"""
    # Get session
    session = db.get(GameSession, session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found"
        )
    
    # Check permissions
    if current_user and session.user_id != current_user.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied"
        )
    
    # Reset session
    session.move_count = 0
    session.current_year = 0
    session.current_stage = "foundation"
    
    # TODO: Delete timeline events and map data
    
    db.add(session)
    db.commit()
    
    # Reset card engine
    card_engine.reset_session()
    
    return {"message": "Simulation reset successfully"}

@router.get("/stages")
async def get_available_stages():
    """Get available game stages"""
    return {
        "stages": [
            {
                "id": stage_id,
                "name": deck.name,
                "remaining_cards": len(deck.cards),
                "drawn_cards": len(deck.drawn_cards)
            }
            for stage_id, deck in card_engine.decks.items()
        ]
    }

