// Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
// Phase: redesign
// Date: 2025-01-27
// Purpose: Card drawing interface with deck configuration and stages-and-powers overlay

import { useState, useCallback, useEffect } from 'react'
import { Play as PlayIcon, Shuffle, Settings, X, Copy, Download, Trash2, History } from 'lucide-react'

interface Card {
  suit: '♠' | '♥' | '♣' | '♦'
  value: string
  id: string
}

interface DrawRecord {
  id: string
  card: Card
  timestamp: Date
  stage?: string
  power?: string
}

interface PowerData {
  stage: string
  suit?: string
  type?: 'disaster' | 'joker'
  power: string
  description: string
  fantasticalDescription?: string
  examples: string
}

const SUITS: Card['suit'][] = ['♠', '♥', '♣', '♦']
const JOKER = 'Joker'

const SUIT_TO_POWER_NAME: Record<string, Record<string, string>> = {
  'genesis': {
    '♠': 'earth',
    '♥': 'water',
    '♣': 'plant',
    '♦': 'feature',
  },
  'primal': {
    '♠': 'settlement',
    '♥': 'tradition',
    '♣': 'resource',
    '♦': 'skill',
  },
  'civilization': {
    '♠': 'construction',
    '♥': 'enlightenment',
    '♣': 'expansion',
    '♦': 'diplomacy',
  },
  'intrigue': {
    '♠': 'conflict',
    '♥': 'cooperation',
    '♣': 'scheme',
    '♦': 'myth',
  },
}

const STAGES = [
  { id: 'genesis', name: 'Genesis' },
  { id: 'primal', name: 'Primal' },
  { id: 'civilization', name: 'Civilization' },
  { id: 'intrigue', name: 'Intrigue' },
]

function shuffleDeck(deck: Card[]): Card[] {
  const shuffled = [...deck]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
      ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

function getCardDisplay(card: Card): { display: string; color: string; bgColor: string } {
  if (card.value === JOKER) {
    return { display: JOKER, color: 'text-purple-600', bgColor: 'bg-purple-50 dark:bg-purple-900/20' }
  }

  const suitColors: Record<Card['suit'], { text: string; bg: string }> = {
    '♠': { text: 'text-gray-900 dark:text-gray-100', bg: 'bg-white dark:bg-gray-800' },
    '♥': { text: 'text-red-600 dark:text-red-400', bg: 'bg-white dark:bg-gray-800' },
    '♣': { text: 'text-green-700 dark:text-green-400', bg: 'bg-white dark:bg-gray-800' },
    '♦': { text: 'text-blue-600 dark:text-blue-400', bg: 'bg-white dark:bg-gray-800' },
  }

  const colors = suitColors[card.suit]
  return {
    display: `${card.value}${card.suit}`,
    color: colors.text,
    bgColor: colors.bg,
  }
}

async function loadPowerData(stage: string, card: Card): Promise<PowerData | null> {
  try {
    if (card.value === JOKER) {
      const response = await fetch(`/data/${stage}-joker.json`)
      if (response.ok) {
        return await response.json()
      }
    } else if (card.value === 'A') {
      const response = await fetch(`/data/${stage}-disaster.json`)
      if (response.ok) {
        return await response.json()
      }
    } else {
      const powerName = SUIT_TO_POWER_NAME[stage]?.[card.suit]
      if (powerName) {
        const response = await fetch(`/data/${stage}-${powerName}.json`)
        if (response.ok) {
          return await response.json()
        }
      }
    }
  } catch (error) {
    console.error('Error loading power data:', error)
  }
  return null
}

export function Play() {
  const [deck, setDeck] = useState<Card[]>([])
  const [drawnCard, setDrawnCard] = useState<Card | null>(null)
  const [drawHistory, setDrawHistory] = useState<DrawRecord[]>([])
  const [showConfig, setShowConfig] = useState(false)
  const [showHistory, setShowHistory] = useState(false)
  const [stagesEnabled, setStagesEnabled] = useState(true) // On by default
  const [selectedStage, setSelectedStage] = useState('genesis') // Start in first stage
  const [powerData, setPowerData] = useState<PowerData | null>(null)

  // Deck configuration
  const [numberRange, setNumberRange] = useState<[number, number]>([2, 10]) // Slider for numbered cards
  const [faceCards, setFaceCards] = useState<Record<string, boolean>>({ J: true, Q: true, K: true })
  const [aceCount, setAceCount] = useState(4) // 0-4
  const [jokerCount, setJokerCount] = useState(2) // 0-2

  const buildDeck = useCallback(() => {
    const newDeck: Card[] = []

    for (const suit of SUITS) {
      // Add numbered cards based on range
      for (let i = numberRange[0]; i <= numberRange[1]; i++) {
        const value = i.toString()
        newDeck.push({ suit, value, id: `${suit}-${value}` })
      }

      // Add face cards based on selection
      for (const [face, included] of Object.entries(faceCards)) {
        if (included) {
          newDeck.push({ suit, value: face, id: `${suit}-${face}` })
        }
      }

      // Add aces
      for (let i = 0; i < aceCount; i++) {
        newDeck.push({ suit, value: 'A', id: `${suit}-A-${i}` })
      }
    }

    // Add jokers
    for (let i = 0; i < jokerCount; i++) {
      newDeck.push({ suit: '♠', value: JOKER, id: `joker-${i}` })
    }

    return shuffleDeck(newDeck)
  }, [numberRange, faceCards, aceCount, jokerCount])

  // Initialize deck on mount
  useEffect(() => {
    setDeck(buildDeck())
  }, [buildDeck])

  // Load power data when card is drawn
  useEffect(() => {
    if (drawnCard && stagesEnabled) {
      loadPowerData(selectedStage, drawnCard).then(setPowerData)
    } else {
      setPowerData(null)
    }
  }, [drawnCard, selectedStage, stagesEnabled])

  const handleDrawCard = async () => {
    if (deck.length === 0) {
      alert('Deck is empty! Reset the deck to draw more cards.')
      return
    }

    const newDeck = [...deck]
    const card = newDeck.pop()!
    setDeck(newDeck)
    setDrawnCard(card)

    // Load power data for the record
    let power: string | undefined = undefined
    if (stagesEnabled) {
      const data = await loadPowerData(selectedStage, card)
      power = data?.power
    }

    const record: DrawRecord = {
      id: `${Date.now()}-${Math.random()}`,
      card,
      timestamp: new Date(),
      stage: stagesEnabled ? selectedStage : undefined,
      power,
    }

    setDrawHistory([...drawHistory, record])
  }

  const handleResetDeck = () => {
    const newDeck = buildDeck()
    setDeck(newDeck)
    setDrawnCard(null)
    setPowerData(null)
  }

  const handleResetHistory = () => {
    if (confirm('Are you sure you want to clear the draw history?')) {
      setDrawHistory([])
    }
  }

  const handleCopyHistory = () => {
    const text = drawHistory
      .map((record) => {
        const { display } = getCardDisplay(record.card)
        let line = `${display}`
        if (record.stage && record.power) {
          line += ` - ${record.stage}: ${record.power}`
        }
        line += ` (${record.timestamp.toLocaleString()})`
        return line
      })
      .join('\n')

    navigator.clipboard.writeText(text)
    alert('History copied to clipboard!')
  }

  const handleExportHistory = () => {
    const data = drawHistory.map((record) => ({
      card: `${record.card.value}${record.card.suit}`,
      stage: record.stage || null,
      power: record.power || null,
      timestamp: record.timestamp.toISOString(),
    }))

    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `draw-history-${new Date().toISOString().split('T')[0]}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const applyPreset = (preset: 'all' | 'short') => {
    if (preset === 'all') {
      setNumberRange([2, 10])
      setFaceCards({ J: true, Q: true, K: true })
      setAceCount(4)
      setJokerCount(2)
    } else if (preset === 'short') {
      setNumberRange([2, 6])
      setFaceCards({ J: false, Q: false, K: true })
      setAceCount(2)
      setJokerCount(1)
    }
    // Deck will rebuild automatically via useEffect
  }

  const isFantastical = drawnCard ? ['J', 'Q', 'K'].includes(drawnCard.value) : false
  const { color, bgColor } = drawnCard ? getCardDisplay(drawnCard) : { color: '', bgColor: '' }

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-4xl font-bold">Play</h1>
        <p className="text-muted-foreground">Draw cards from your deck</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Card Area - Split Layout */}
        <div className="lg:col-span-2 space-y-6">
          {/* Playing Area - Left/Right Split */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Left: Card Display */}
            <div className="card p-6">
              <div className="flex flex-col items-center justify-center min-h-[400px]">
                {drawnCard ? (
                  <div className={`w-full max-w-xs aspect-[5/7] ${bgColor} rounded-xl border-4 border-gray-300 dark:border-gray-600 shadow-2xl flex flex-col items-center justify-center p-8 relative`}>
                    {/* Corner value (top-left) */}
                    <div className={`absolute top-2 left-3 text-2xl font-bold ${color}`}>
                      {drawnCard.value}
                    </div>
                    <div className={`absolute top-8 left-3 text-xl ${color}`}>
                      {drawnCard.suit}
                    </div>
                    {/* Center display */}
                    <div className={`text-7xl font-bold ${color} mb-4`}>
                      {drawnCard.value === JOKER ? '🃏' : drawnCard.suit}
                    </div>
                    {drawnCard.value !== JOKER && (
                      <div className={`text-5xl font-bold ${color}`}>
                        {drawnCard.value}
                      </div>
                    )}
                    {/* Corner value (bottom-right, rotated) */}
                    {drawnCard.value !== JOKER && (
                      <>
                        <div className={`absolute bottom-2 right-3 text-2xl font-bold ${color} rotate-180`}>
                          {drawnCard.value}
                        </div>
                        <div className={`absolute bottom-8 right-3 text-xl ${color} rotate-180`}>
                          {drawnCard.suit}
                        </div>
                      </>
                    )}
                  </div>
                ) : (
                  <div className="text-center text-muted-foreground">
                    <div className="text-6xl mb-4">🃏</div>
                    <p className="text-lg">Click "Draw Card" to begin</p>
                    <p className="text-sm mt-2">Deck: {deck.length} cards remaining</p>
                  </div>
                )}
              </div>
            </div>

            {/* Right: Powers/Stage/Description */}
            <div className="card p-6 space-y-4">
              {drawnCard && stagesEnabled && powerData ? (
                <>
                  <div>
                    <div className="text-sm text-muted-foreground mb-1">Power</div>
                    <div className="text-2xl font-semibold">
                      {isFantastical && powerData.fantasticalDescription ? 'Fantastical ' : ''}
                      {powerData.power}
                    </div>
                  </div>

                  <div>
                    <div className="text-sm text-muted-foreground mb-1">Stage</div>
                    <div className="text-lg font-medium">
                      {STAGES.find(s => s.id === selectedStage)?.name}
                    </div>
                  </div>

                  <div>
                    <div className="text-sm text-muted-foreground mb-1">Description</div>
                    <div className="text-sm">
                      {isFantastical && powerData.fantasticalDescription
                        ? powerData.fantasticalDescription
                        : powerData.description}
                    </div>
                  </div>

                  <div>
                    <div className="text-sm text-muted-foreground mb-1">Examples</div>
                    <div className="text-sm text-muted-foreground">
                      {powerData.examples}
                    </div>
                  </div>
                </>
              ) : drawnCard ? (
                <div className="text-center text-muted-foreground">
                  <p>Enable Stages & Powers to see details</p>
                </div>
              ) : (
                <div className="text-center text-muted-foreground">
                  <p>Draw a card to see its power</p>
                </div>
              )}
            </div>
          </div>

          {/* Controls */}
          <div className="flex flex-wrap gap-4">
            <button
              onClick={handleDrawCard}
              disabled={deck.length === 0}
              className="btn-primary flex items-center space-x-2 px-6 py-3 text-lg disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <PlayIcon className="h-5 w-5" />
              <span>Draw Card</span>
            </button>
            <button
              onClick={handleResetDeck}
              className="btn-outline flex items-center space-x-2 px-6 py-3"
            >
              <Shuffle className="h-5 w-5" />
              <span>Reset Deck</span>
            </button>
            <button
              onClick={() => setShowConfig(!showConfig)}
              className="btn-outline flex items-center space-x-2 px-6 py-3"
            >
              <Settings className="h-5 w-5" />
              <span>Configure</span>
            </button>
            <button
              onClick={() => setShowHistory(!showHistory)}
              className="btn-outline flex items-center space-x-2 px-6 py-3"
            >
              <History className="h-5 w-5" />
              <span>History ({drawHistory.length})</span>
            </button>
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          {/* Configuration Panel */}
          {showConfig && (
            <div className="card p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-xl font-semibold">Configuration</h3>
                <button
                  onClick={() => setShowConfig(false)}
                  className="p-1 hover:bg-accent rounded"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>

              <div className="space-y-6">
                {/* Presets */}
                <div>
                  <label className="text-sm font-medium mb-2 block">Presets</label>
                  <div className="flex gap-2">
                    <button
                      onClick={() => applyPreset('all')}
                      className="btn-outline flex-1 text-sm py-2"
                    >
                      All - Normal Game
                    </button>
                    <button
                      onClick={() => applyPreset('short')}
                      className="btn-outline flex-1 text-sm py-2"
                    >
                      Short Game
                    </button>
                  </div>
                </div>

                {/* Numbered Cards Slider */}
                <div>
                  <label className="text-sm font-medium mb-2 block">
                    Numbered Cards: {numberRange[0]}-{numberRange[1]}
                  </label>
                  <div className="space-y-2">
                    <div className="flex items-center gap-4">
                      <span className="text-xs text-muted-foreground w-12">Min:</span>
                      <input
                        type="range"
                        min="2"
                        max="10"
                        value={numberRange[0]}
                        onChange={(e) => {
                          const min = parseInt(e.target.value)
                          setNumberRange([min, Math.max(min, numberRange[1])])
                        }}
                        className="flex-1"
                      />
                      <span className="text-sm font-medium w-8">{numberRange[0]}</span>
                    </div>
                    <div className="flex items-center gap-4">
                      <span className="text-xs text-muted-foreground w-12">Max:</span>
                      <input
                        type="range"
                        min="2"
                        max="10"
                        value={numberRange[1]}
                        onChange={(e) => {
                          const max = parseInt(e.target.value)
                          setNumberRange([Math.min(numberRange[0], max), max])
                        }}
                        className="flex-1"
                      />
                      <span className="text-sm font-medium w-8">{numberRange[1]}</span>
                    </div>
                  </div>
                </div>

                {/* Face Cards */}
                <div>
                  <label className="text-sm font-medium mb-2 block">Face Cards</label>
                  <div className="flex gap-2">
                    {(['J', 'Q', 'K'] as const).map((face) => (
                      <button
                        key={face}
                        onClick={() => setFaceCards({ ...faceCards, [face]: !faceCards[face] })}
                        className={`flex-1 py-2 px-3 rounded border ${faceCards[face]
                            ? 'bg-primary text-primary-foreground border-primary'
                            : 'bg-background border-border hover:bg-accent'
                          }`}
                      >
                        {face}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Aces */}
                <div>
                  <label className="text-sm font-medium mb-2 block">
                    Aces: {aceCount}
                  </label>
                  <input
                    type="range"
                    min="0"
                    max="4"
                    value={aceCount}
                    onChange={(e) => setAceCount(parseInt(e.target.value))}
                    className="w-full"
                  />
                  <div className="flex justify-between text-xs text-muted-foreground mt-1">
                    <span>0</span>
                    <span>4</span>
                  </div>
                </div>

                {/* Jokers */}
                <div>
                  <label className="text-sm font-medium mb-2 block">
                    Jokers: {jokerCount}
                  </label>
                  <input
                    type="range"
                    min="0"
                    max="2"
                    value={jokerCount}
                    onChange={(e) => setJokerCount(parseInt(e.target.value))}
                    className="w-full"
                  />
                  <div className="flex justify-between text-xs text-muted-foreground mt-1">
                    <span>0</span>
                    <span>2</span>
                  </div>
                </div>

                {/* Stages & Powers */}
                <div className="border-t border-border pt-4">
                  <label className="text-sm font-medium mb-2 block">Stages & Powers</label>
                  <label className="flex items-center space-x-2 mb-3">
                    <input
                      type="checkbox"
                      checked={stagesEnabled}
                      onChange={(e) => setStagesEnabled(e.target.checked)}
                      className="rounded"
                    />
                    <span>Enable Stages & Powers Overlay</span>
                  </label>
                  {stagesEnabled && (
                    <select
                      value={selectedStage}
                      onChange={(e) => setSelectedStage(e.target.value)}
                      className="input w-full"
                    >
                      {STAGES.map((stage) => (
                        <option key={stage.id} value={stage.id}>
                          {stage.name}
                        </option>
                      ))}
                    </select>
                  )}
                </div>

                <button
                  onClick={() => {
                    const newDeck = buildDeck()
                    setDeck(newDeck)
                    setDrawnCard(null)
                    setPowerData(null)
                  }}
                  className="btn-primary w-full"
                >
                  Apply Configuration
                </button>
              </div>
            </div>
          )}

          {/* Deck Info */}
          <div className="card p-6">
            <h3 className="text-lg font-semibold mb-4">Deck Status</h3>
            <div className="space-y-2">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Cards Remaining</span>
                <span className="font-semibold">{deck.length}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Cards Drawn</span>
                <span className="font-semibold">{drawHistory.length}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Draw History */}
      {showHistory && (
        <div className="card p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-xl font-semibold">Draw History</h3>
            <div className="flex items-center space-x-2">
              <button
                onClick={handleCopyHistory}
                disabled={drawHistory.length === 0}
                className="btn-outline flex items-center space-x-2 px-4 py-2 text-sm disabled:opacity-50"
                title="Copy to clipboard"
              >
                <Copy className="h-4 w-4" />
                <span>Copy</span>
              </button>
              <button
                onClick={handleExportHistory}
                disabled={drawHistory.length === 0}
                className="btn-outline flex items-center space-x-2 px-4 py-2 text-sm disabled:opacity-50"
                title="Export as JSON"
              >
                <Download className="h-4 w-4" />
                <span>Export</span>
              </button>
              <button
                onClick={handleResetHistory}
                disabled={drawHistory.length === 0}
                className="btn-outline flex items-center space-x-2 px-4 py-2 text-sm disabled:opacity-50 text-destructive"
                title="Clear history"
              >
                <Trash2 className="h-4 w-4" />
                <span>Clear</span>
              </button>
              <button
                onClick={() => setShowHistory(false)}
                className="p-1 hover:bg-accent rounded"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>

          {drawHistory.length === 0 ? (
            <p className="text-center text-muted-foreground py-8">
              No cards drawn yet. Start drawing to see history here.
            </p>
          ) : (
            <div className="space-y-2 max-h-96 overflow-y-auto">
              {drawHistory.slice().reverse().map((record) => {
                const { display, color } = getCardDisplay(record.card)
                return (
                  <div
                    key={record.id}
                    className="flex items-center justify-between p-3 bg-muted/50 rounded-lg"
                  >
                    <div className="flex items-center space-x-4">
                      <span className={`text-2xl font-bold ${color}`}>{display}</span>
                      <div>
                        {record.power && (
                          <div className="font-semibold">{record.power}</div>
                        )}
                        {record.stage && (
                          <div className="text-sm text-muted-foreground">
                            {STAGES.find(s => s.id === record.stage)?.name}
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="text-sm text-muted-foreground">
                      {record.timestamp.toLocaleTimeString()}
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>
      )}
    </div>
  )
}
