// Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
// Phase: redesign
// Date: 2025-01-27
// Purpose: Card drawing interface with deck configuration and stages-and-powers overlay

import { useState, useCallback } from 'react'
import { Play as PlayIcon, Shuffle, Settings, X, Copy, Download, Trash2, History } from 'lucide-react'

interface Card {
  suit: '♠' | '♥' | '♣' | '♦'
  value: string
  id: string
}

interface DrawRecord {
  id: string
  card: Card
  timestamp: Date
  stage?: string
  power?: string
}

const SUITS: Card['suit'][] = ['♠', '♥', '♣', '♦']
const VALUES = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
const JOKER = 'Joker'

const STAGE_POWERS: Record<string, Record<string, string>> = {
  'genesis': {
    '♠': 'Earth',
    '♥': 'Water',
    '♣': 'Plant',
    '♦': 'Feature',
  },
  'primal': {
    '♠': 'Settlement',
    '♥': 'Tradition',
    '♣': 'Resource',
    '♦': 'Skill',
  },
  'civilization': {
    '♠': 'Construction',
    '♥': 'Enlightenment',
    '♣': 'Expansion',
    '♦': 'Diplomacy',
  },
  'intrigue': {
    '♠': 'Conflict',
    '♥': 'Cooperation',
    '♣': 'Scheme',
    '♦': 'Myth',
  },
}

const STAGES = [
  { id: 'genesis', name: 'Genesis' },
  { id: 'primal', name: 'Primal' },
  { id: 'civilization', name: 'Civilization' },
  { id: 'intrigue', name: 'Intrigue' },
]

function createFullDeck(): Card[] {
  const deck: Card[] = []
  for (const suit of SUITS) {
    for (const value of VALUES) {
      deck.push({ suit, value, id: `${suit}-${value}` })
    }
  }
  // Add two jokers
  deck.push({ suit: '♠', value: JOKER, id: 'joker-1' })
  deck.push({ suit: '♥', value: JOKER, id: 'joker-2' })
  return deck
}

function shuffleDeck(deck: Card[]): Card[] {
  const shuffled = [...deck]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

function getCardDisplay(card: Card): { display: string; color: string } {
  if (card.value === JOKER) {
    return { display: JOKER, color: 'text-purple-600' }
  }
  
  const suitColors: Record<Card['suit'], string> = {
    '♠': 'text-gray-900',
    '♥': 'text-red-600',
    '♣': 'text-green-700',
    '♦': 'text-blue-600',
  }
  
  return {
    display: `${card.value}${card.suit}`,
    color: suitColors[card.suit],
  }
}

export function Play() {
  const [deck, setDeck] = useState<Card[]>(shuffleDeck(createFullDeck()))
  const [drawnCard, setDrawnCard] = useState<Card | null>(null)
  const [drawHistory, setDrawHistory] = useState<DrawRecord[]>([])
  const [showConfig, setShowConfig] = useState(false)
  const [showHistory, setShowHistory] = useState(false)
  const [stagesEnabled, setStagesEnabled] = useState(false)
  const [selectedStage, setSelectedStage] = useState('genesis')
  
  // Deck configuration
  const [includeNumbers, setIncludeNumbers] = useState(true)
  const [includeFaces, setIncludeFaces] = useState(true)
  const [includeAces, setIncludeAces] = useState(true)
  const [includeJokers, setIncludeJokers] = useState(true)

  const buildDeck = useCallback(() => {
    const newDeck: Card[] = []
    
    for (const suit of SUITS) {
      if (includeNumbers) {
        for (const value of VALUES.slice(0, 9)) { // 2-10
          newDeck.push({ suit, value, id: `${suit}-${value}` })
        }
      }
      if (includeFaces) {
        for (const value of VALUES.slice(9, 12)) { // J, Q, K
          newDeck.push({ suit, value, id: `${suit}-${value}` })
        }
      }
      if (includeAces) {
        newDeck.push({ suit, value: 'A', id: `${suit}-A` })
      }
    }
    
    if (includeJokers) {
      newDeck.push({ suit: '♠', value: JOKER, id: 'joker-1' })
      newDeck.push({ suit: '♥', value: JOKER, id: 'joker-2' })
    }
    
    return shuffleDeck(newDeck)
  }, [includeNumbers, includeFaces, includeAces, includeJokers])

  const handleDrawCard = () => {
    if (deck.length === 0) {
      alert('Deck is empty! Reset the deck to draw more cards.')
      return
    }
    
    const newDeck = [...deck]
    const card = newDeck.pop()!
    setDeck(newDeck)
    setDrawnCard(card)
    
    const power = stagesEnabled && card.value !== JOKER && card.value !== 'A'
      ? STAGE_POWERS[selectedStage]?.[card.suit] || null
      : null
    
    const record: DrawRecord = {
      id: `${Date.now()}-${Math.random()}`,
      card,
      timestamp: new Date(),
      stage: stagesEnabled ? selectedStage : undefined,
      power: power || undefined,
    }
    
    setDrawHistory([...drawHistory, record])
  }

  const handleResetDeck = () => {
    const newDeck = buildDeck()
    setDeck(newDeck)
    setDrawnCard(null)
  }

  const handleResetHistory = () => {
    if (confirm('Are you sure you want to clear the draw history?')) {
      setDrawHistory([])
    }
  }

  const handleCopyHistory = () => {
    const text = drawHistory
      .map((record) => {
        const { display } = getCardDisplay(record.card)
        let line = `${display}`
        if (record.stage && record.power) {
          line += ` - ${record.stage}: ${record.power}`
        }
        line += ` (${record.timestamp.toLocaleString()})`
        return line
      })
      .join('\n')
    
    navigator.clipboard.writeText(text)
    alert('History copied to clipboard!')
  }

  const handleExportHistory = () => {
    const data = drawHistory.map((record) => ({
      card: `${record.card.value}${record.card.suit}`,
      stage: record.stage || null,
      power: record.power || null,
      timestamp: record.timestamp.toISOString(),
    }))
    
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `draw-history-${new Date().toISOString().split('T')[0]}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const getPowerForCard = (card: Card): string | null => {
    if (card.value === JOKER) return 'Any Fantastical Power'
    if (card.value === 'A') return 'Natural Disaster'
    if (['J', 'Q', 'K'].includes(card.value)) {
      return stagesEnabled ? `Fantastical ${STAGE_POWERS[selectedStage]?.[card.suit] || ''}` : null
    }
    return stagesEnabled ? STAGE_POWERS[selectedStage]?.[card.suit] || null : null
  }

  const power = drawnCard ? getPowerForCard(drawnCard) : null
  const { display, color } = drawnCard ? getCardDisplay(drawnCard) : { display: '', color: '' }

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="text-center space-y-2">
        <h1 className="text-4xl font-bold">Play</h1>
        <p className="text-muted-foreground">Draw cards from your deck</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Card Area */}
        <div className="lg:col-span-2 space-y-6">
          {/* Card Display */}
          <div className="card p-8">
            <div className="flex flex-col items-center justify-center min-h-[400px] space-y-6">
              {drawnCard ? (
                <>
                  <div className={`text-8xl font-bold ${color} mb-4`}>
                    {display}
                  </div>
                  {power && (
                    <div className="text-center space-y-2">
                      <div className="text-sm text-muted-foreground">Power</div>
                      <div className="text-2xl font-semibold">{power}</div>
                      {stagesEnabled && selectedStage && (
                        <div className="text-sm text-muted-foreground">
                          Stage: {STAGES.find(s => s.id === selectedStage)?.name}
                        </div>
                      )}
                    </div>
                  )}
                  {drawnCard.value === 'A' && (
                    <div className="text-center mt-4 p-4 bg-yellow-50 dark:bg-yellow-900/20 rounded-lg">
                      <div className="font-semibold text-yellow-800 dark:text-yellow-200">
                        Natural Disaster
                      </div>
                      <div className="text-sm text-yellow-700 dark:text-yellow-300 mt-1">
                        Decide what happens!
                      </div>
                    </div>
                  )}
                  {drawnCard.value === JOKER && (
                    <div className="text-center mt-4 p-4 bg-purple-50 dark:bg-purple-900/20 rounded-lg">
                      <div className="font-semibold text-purple-800 dark:text-purple-200">
                        Joker
                      </div>
                      <div className="text-sm text-purple-700 dark:text-purple-300 mt-1">
                        Any Fantastical Power
                      </div>
                    </div>
                  )}
                </>
              ) : (
                <div className="text-center text-muted-foreground">
                  <div className="text-6xl mb-4">🃏</div>
                  <p className="text-lg">Click "Draw Card" to begin</p>
                  <p className="text-sm mt-2">Deck: {deck.length} cards remaining</p>
                </div>
              )}
            </div>
          </div>

          {/* Controls */}
          <div className="flex flex-wrap gap-4">
            <button
              onClick={handleDrawCard}
              disabled={deck.length === 0}
              className="btn-primary flex items-center space-x-2 px-6 py-3 text-lg disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <PlayIcon className="h-5 w-5" />
              <span>Draw Card</span>
            </button>
            <button
              onClick={handleResetDeck}
              className="btn-outline flex items-center space-x-2 px-6 py-3"
            >
              <Shuffle className="h-5 w-5" />
              <span>Reset Deck</span>
            </button>
            <button
              onClick={() => setShowConfig(!showConfig)}
              className="btn-outline flex items-center space-x-2 px-6 py-3"
            >
              <Settings className="h-5 w-5" />
              <span>Configure</span>
            </button>
            <button
              onClick={() => setShowHistory(!showHistory)}
              className="btn-outline flex items-center space-x-2 px-6 py-3"
            >
              <History className="h-5 w-5" />
              <span>History ({drawHistory.length})</span>
            </button>
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          {/* Configuration Panel */}
          {showConfig && (
            <div className="card p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-xl font-semibold">Configuration</h3>
                <button
                  onClick={() => setShowConfig(false)}
                  className="p-1 hover:bg-accent rounded"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>
              
              <div className="space-y-4">
                <div>
                  <label className="text-sm font-medium mb-2 block">Deck Contents</label>
                  <div className="space-y-2">
                    <label className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        checked={includeNumbers}
                        onChange={(e) => setIncludeNumbers(e.target.checked)}
                        className="rounded"
                      />
                      <span>Numbers (2-10)</span>
                    </label>
                    <label className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        checked={includeFaces}
                        onChange={(e) => setIncludeFaces(e.target.checked)}
                        className="rounded"
                      />
                      <span>Face Cards (J, Q, K)</span>
                    </label>
                    <label className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        checked={includeAces}
                        onChange={(e) => setIncludeAces(e.target.checked)}
                        className="rounded"
                      />
                      <span>Aces</span>
                    </label>
                    <label className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        checked={includeJokers}
                        onChange={(e) => setIncludeJokers(e.target.checked)}
                        className="rounded"
                      />
                      <span>Jokers</span>
                    </label>
                  </div>
                </div>

                <div className="border-t border-border pt-4">
                  <label className="text-sm font-medium mb-2 block">Stages & Powers</label>
                  <label className="flex items-center space-x-2 mb-3">
                    <input
                      type="checkbox"
                      checked={stagesEnabled}
                      onChange={(e) => setStagesEnabled(e.target.checked)}
                      className="rounded"
                    />
                    <span>Enable Stages & Powers Overlay</span>
                  </label>
                  {stagesEnabled && (
                    <select
                      value={selectedStage}
                      onChange={(e) => setSelectedStage(e.target.value)}
                      className="input w-full"
                    >
                      {STAGES.map((stage) => (
                        <option key={stage.id} value={stage.id}>
                          {stage.name}
                        </option>
                      ))}
                    </select>
                  )}
                </div>

                <button
                  onClick={() => {
                    setDeck(buildDeck())
                    setDrawnCard(null)
                  }}
                  className="btn-primary w-full"
                >
                  Apply Configuration
                </button>
              </div>
            </div>
          )}

          {/* Deck Info */}
          <div className="card p-6">
            <h3 className="text-lg font-semibold mb-4">Deck Status</h3>
            <div className="space-y-2">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Cards Remaining</span>
                <span className="font-semibold">{deck.length}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Cards Drawn</span>
                <span className="font-semibold">{drawHistory.length}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Draw History */}
      {showHistory && (
        <div className="card p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-xl font-semibold">Draw History</h3>
            <div className="flex items-center space-x-2">
              <button
                onClick={handleCopyHistory}
                disabled={drawHistory.length === 0}
                className="btn-outline flex items-center space-x-2 px-4 py-2 text-sm disabled:opacity-50"
                title="Copy to clipboard"
              >
                <Copy className="h-4 w-4" />
                <span>Copy</span>
              </button>
              <button
                onClick={handleExportHistory}
                disabled={drawHistory.length === 0}
                className="btn-outline flex items-center space-x-2 px-4 py-2 text-sm disabled:opacity-50"
                title="Export as JSON"
              >
                <Download className="h-4 w-4" />
                <span>Export</span>
              </button>
              <button
                onClick={handleResetHistory}
                disabled={drawHistory.length === 0}
                className="btn-outline flex items-center space-x-2 px-4 py-2 text-sm disabled:opacity-50 text-destructive"
                title="Clear history"
              >
                <Trash2 className="h-4 w-4" />
                <span>Clear</span>
              </button>
              <button
                onClick={() => setShowHistory(false)}
                className="p-1 hover:bg-accent rounded"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>
          
          {drawHistory.length === 0 ? (
            <p className="text-center text-muted-foreground py-8">
              No cards drawn yet. Start drawing to see history here.
            </p>
          ) : (
            <div className="space-y-2 max-h-96 overflow-y-auto">
              {drawHistory.slice().reverse().map((record) => {
                const { display, color } = getCardDisplay(record.card)
                return (
                  <div
                    key={record.id}
                    className="flex items-center justify-between p-3 bg-muted/50 rounded-lg"
                  >
                    <div className="flex items-center space-x-4">
                      <span className={`text-2xl font-bold ${color}`}>{display}</span>
                      <div>
                        {record.power && (
                          <div className="font-semibold">{record.power}</div>
                        )}
                        {record.stage && (
                          <div className="text-sm text-muted-foreground">
                            {STAGES.find(s => s.id === record.stage)?.name}
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="text-sm text-muted-foreground">
                      {record.timestamp.toLocaleTimeString()}
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

