// Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
// Phase: redesign
// Date: 2025-01-27
// Purpose: Wiki-style rules page with navigation and formatted content

import React, { useState, useEffect } from 'react'
import { BookOpen, Menu, X } from 'lucide-react'

interface NavItem {
  id: string
  title: string
  level: number
  children?: NavItem[]
}

const NAVIGATION: NavItem[] = [
  { id: 'introduction', title: 'Introduction', level: 1 },
  { id: 'guide-to-world-building', title: 'Guide to World Building', level: 1 },
  {
    id: 'preparation-and-requirements',
    title: 'Preparation and Requirements',
    level: 1,
    children: [
      { id: 'what-you-will-need', title: 'What you will need', level: 2 },
      { id: 'how-long-it-will-take', title: 'How long it will take', level: 2 },
    ],
  },
  {
    id: 'system',
    title: 'System',
    level: 1,
    children: [
      { id: 'setup', title: 'Setup', level: 2 },
      { id: 'playing-a-stage', title: 'Playing a Stage', level: 2 },
      { id: 'powers', title: 'Powers', level: 2 },
      { id: 'cards', title: 'Cards', level: 2 },
    ],
  },
  {
    id: 'stages-and-powers',
    title: 'Stages and Powers',
    level: 1,
    children: [
      { id: 'timeline-and-history', title: 'Timeline and History', level: 2 },
      { id: 'natural-disasters', title: 'Natural Disasters', level: 2 },
      {
        id: '1.-genesis',
        title: '1. Genesis',
        level: 2,
        children: [
          { id: '(♠)---earth', title: '(♠) - Earth', level: 3 },
          { id: '(♥)---water', title: '(♥) - Water', level: 3 },
          { id: '(♣)---plant', title: '(♣) - Plant', level: 3 },
          { id: '(♦)---feature', title: '(♦) - Feature', level: 3 },
        ],
      },
      {
        id: '2.-primal',
        title: '2. Primal',
        level: 2,
        children: [
          { id: '(♠)---settlement', title: '(♠) - Settlement', level: 3 },
          { id: '(♥)---tradition', title: '(♥) - Tradition', level: 3 },
          { id: '(♣)---resource', title: '(♣) - Resource', level: 3 },
          { id: '(♦)---skill', title: '(♦) - Skill', level: 3 },
        ],
      },
      {
        id: '3.-civilization',
        title: '3. Civilization',
        level: 2,
        children: [
          { id: '(♠)---construction', title: '(♠) - Construction', level: 3 },
          { id: '(♥)---enlightenment', title: '(♥) - Enlightenment', level: 3 },
          { id: '(♣)---expansion', title: '(♣) - Expansion', level: 3 },
          { id: '(♦)---diplomacy', title: '(♦) - Diplomacy', level: 3 },
        ],
      },
      {
        id: '4.-intrigue',
        title: '4. Intrigue',
        level: 2,
        children: [
          { id: '(♠)---conflict', title: '(♠) - Conflict', level: 3 },
          { id: '(♥)---cooperation', title: '(♥) - Cooperation', level: 3 },
          { id: '(♣)---scheme', title: '(♣) - Scheme', level: 3 },
          { id: '(♦)---myth', title: '(♦) - Myth', level: 3 },
        ],
      },
    ],
  },
  { id: 'glossary-of-terms', title: 'Glossary of Terms', level: 1 },
  { id: 'reference-table', title: 'Reference Table', level: 1 },
  { id: 'acknowledgements', title: 'Acknowledgements', level: 1 },
]

export function Rules() {
  const [activeSection, setActiveSection] = useState('introduction')
  const [sidebarOpen, setSidebarOpen] = useState(false)

  useEffect(() => {
    const handleHashChange = () => {
      const hash = window.location.hash.slice(1)
      if (hash) {
        setActiveSection(hash)
        document.getElementById(hash)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
      }
    }

    handleHashChange()
    window.addEventListener('hashchange', handleHashChange)
    return () => window.removeEventListener('hashchange', handleHashChange)
  }, [])

  const scrollToSection = (id: string) => {
    setActiveSection(id)
    setSidebarOpen(false)
    window.location.hash = id
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  const renderNavItem = (item: NavItem) => (
    <div key={item.id}>
      <button
        onClick={() => scrollToSection(item.id)}
        className={`w-full text-left px-3 py-2 rounded-md transition-colors ${
          activeSection === item.id
            ? 'bg-primary text-primary-foreground'
            : 'text-muted-foreground hover:text-foreground hover:bg-accent'
        }`}
        style={{ paddingLeft: `${(item.level - 1) * 1 + 0.75}rem` }}
      >
        {item.title}
      </button>
      {item.children && (
        <div className="ml-2 mt-1 space-y-1">
          {item.children.map(renderNavItem)}
        </div>
      )}
    </div>
  )

  return (
    <div className="max-w-7xl mx-auto">
      <div className="flex gap-8">
        {/* Sidebar Navigation */}
        <aside
          className={`${
            sidebarOpen ? 'fixed' : 'hidden'
          } lg:block lg:sticky lg:top-8 h-fit w-64 flex-shrink-0 bg-card border rounded-lg p-4 z-10 lg:z-auto`}
          style={{ maxHeight: 'calc(100vh - 4rem)' }}
        >
          <div className="flex items-center justify-between mb-4 lg:hidden">
            <h2 className="font-semibold">Navigation</h2>
            <button
              onClick={() => setSidebarOpen(false)}
              className="p-1 hover:bg-accent rounded"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
          <nav className="space-y-1 overflow-y-auto" style={{ maxHeight: 'calc(100vh - 8rem)' }}>
            {NAVIGATION.map(renderNavItem)}
          </nav>
        </aside>

        {/* Main Content */}
        <div className="flex-1 min-w-0">
          {/* Mobile Menu Button */}
          <div className="lg:hidden mb-4">
            <button
              onClick={() => setSidebarOpen(true)}
              className="btn-outline flex items-center space-x-2"
            >
              <Menu className="h-4 w-4" />
              <span>Menu</span>
            </button>
          </div>

          <div className="card p-8 space-y-8">
            <div className="text-center space-y-2">
              <BookOpen className="h-12 w-12 text-primary mx-auto" />
              <h1 className="text-4xl font-bold">World Building</h1>
              <p className="text-xl text-muted-foreground">Game Rules</p>
            </div>

            <RulesContent />
          </div>
        </div>
      </div>
    </div>
  )
}

function RulesContent() {
  return (
    <div className="prose prose-slate max-w-none">
      <Section id="introduction" title="Introduction">
        <p>
          World building is a game where you and your friends will create a world. The theme of this
          game is Fantasy, and the idea is that you could then later use this world in your other
          role-playing-games, or for a fantasy story.
        </p>
        <p>
          Throughout the game, different players will take turns using different powers to shape a
          world. From its terrain, and up to its civilizations, their cultures, and the wars they
          fight. While this is happening, you will want to write down and record the different
          actions that are happening to use as the history for your world, and to track the
          different races and cultures and their wars and technological developments so that you will
          have a rich world to play in. You will of course, also need to be drawing this world as
          you play, and you will end up with an awesome world map that you can use for your game.
          The added benefit of course, that if you make the world with the same players that will
          be playing in your game, they will be much more connected to the world and already know
          it's history!
        </p>
      </Section>

      <Section id="guide-to-world-building" title="Guide to World Building">
        <p>
          A world is a complex concept with many elements, simplifying it into a system like the one
          here takes certain simplifications. But we can also make certain assumption to make the
          whole process easier and more fun! The system will let you create forests and rivers, but
          that doesn't mean there aren't trees here and there, small groves, or little streams. The
          elements you introduce with the powers in this game aren't the only thing in the game,
          we assume that the world will have hills, rocks, trees, and vegetation, including the
          occasional stream, brook, or pond. The features that his systems powers let you create
          represent significant terrain features, fauna, flora, settlements, and events. In other
          words, don't worry about the small stuff.
        </p>
      </Section>

      <Section id="preparation-and-requirements" title="Preparation and Requirements">
        <SubSection id="what-you-will-need" title="What you will need">
          <p>
            For World Building, you will need a few players, pencils, plenty of paper, and
            preferably a whiteboard with markers, or some other large and easy for all players to
            see and interact with medium on which to draw. (perhaps even playable online with some
            sort of collaborative whiteboard) It works well with a single player doing all the
            drawing, or everyone doing their own thing, whatever you prefer as a group, but a single
            player drawing will usually take slightly more time than otherwise. And lastly you will
            need a normal deck of playing cards (with jokers) this is the Draw Deck.
          </p>
        </SubSection>

        <SubSection id="how-long-it-will-take" title="How long it will take">
          <p>
            Each stage of the game should take between an hour and two hours, depending on how
            detailed you are making the game, and any variant or house rules you may be using.
          </p>
        </SubSection>
      </Section>

      <Section id="system" title="System">
        <p>
          The process of building a world is split into three stages, with a fourth optional stage;
          Genesis, Primal, Civilization, and Intrigue. Each stage is slightly different from the
          others, with focus given to different aspects of building a world.
        </p>
        <p>
          Unlike other "games" or systems, there is no winner or loser when World Building. The
          players are simply creating a world together.
        </p>
        <p>
          During the progression of the game, as the world goes through stages the players are free
          to do anything that they want, they could create mountains in the first stage, only to
          destroy them in the second stage. A player can put two of his creations against each
          other, or even wipe them out completely. Something created by a player is owned by
          everyone.
        </p>

        <SubSection id="setup" title="Setup">
          <p>To set up the game, prepare your playing area. Each player should make sure that:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>They have easy access to the Draw Deck.</li>
            <li>They can see and gesture at locations on the map.</li>
            <li>They have pencil and paper to record actions and make notes.</li>
          </ul>
          <p>
            There are three optional, but recommended, roles that should be assigned or shared by
            players:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Artist, dedicated to drawing the map.</li>
            <li>Historian, dedicated to recording the timeline.</li>
            <li>Keeper, dedicated to tracking various developments.</li>
          </ul>
          <p>
            Now, before you start, you should draw a basic outline of a coastline, and maybe a few
            features as a starting map. If you like you can design a whole seasonal system, with
            tides, and moons, and weather, multiple continents, and etc. But for the purpose of the
            game you will only be needing a single main landmass, a few features, and maybe some
            islands.
          </p>
          <p>Once you've done all that you are ready to start the first stage!</p>
        </SubSection>

        <SubSection id="playing-a-stage" title="Playing a Stage">
          <p>At the start of each stage, shuffle and prepare the Draw Deck.</p>
          <p>Decide how many cards of each type you want to include….</p>
          <p>A stage is played in rounds until all cards have been played.</p>
          <p>
            Each round, players will draw a card from the Draw Deck and play it for everyone to see.
            Placing it faceup in the discard pile.
          </p>
          <p>
            After all the effects are determined, the Artist should depict or draw any relevant
            changes in the map. The Historian should record the actions in the timeline, and the
            Keeper should track any relevant changes in the world.
          </p>
        </SubSection>

        <SubSection id="powers" title="Powers">
          <p>During each stage there are four powers.</p>
          <p>
            Powers can also be made Fantastical by using face cards of the same suit, or a Joker.
          </p>
          <p>
            Fantastical versions of powers are essentially the same as normal powers only
            fantastical, you should decide ahead of time with the rest of the players just how
            fantastical you want to make it. Low and High fantasy can both be easily supported,
            additionally you may decide to remove Fantastical powers from the game completely and
            simply use them as <em>enhanced</em> or <em>better-than-normal</em> versions of the
            powers.
          </p>
          <p>
            Powers can affect any size area on the map, there is no size factor. But you should
            consider carefully how big or small things should be, and to keep room for things and
            not to overcrowd anything. Use your own judgement.
          </p>
        </SubSection>

        <SubSection id="cards" title="Cards">
          <p>During each stage, there are four powers. Each power corresponds to a different card suite.</p>
          <p>The cards numbered 2 through 10 are used for powers of the current stage.</p>
          <p>
            The face cards (Jack, Queen, King) are used to perform Fantastical versions of the
            powers of the current stage.
          </p>
          <p>Aces are Natural Disasters.</p>
          <p>Jokers are Fantastical versions of any power.</p>
        </SubSection>
      </Section>

      <Section id="stages-and-powers" title="Stages and Powers">
        <p>
          Each stage has a focus on a different stage of world building. Here you will find those
          stages, and explanations of how to use them to build the world as well as a list of the
          powers for each age and descriptions of them.
        </p>

        <SubSection id="timeline-and-history" title="Timeline and History">
          <p>
            The stages take place over the history and timeline of the world you are making. When
            deciding the scale of time for the different actions during different stages consider
            the following:
          </p>
          <ol className="list-decimal list-inside space-y-2 ml-4">
            <li>
              Genesis is pre-history, the exact date of actions are not that important and it should
              be assumed that all events in this time happened before recorded history more than
              tens of thousands of years ago
            </li>
            <li>
              Primal is the earliest history, the actions and events in this stage don't need to
              have fixed dates, and have all taken place many thousands of years ago
            </li>
            <li>
              Civilization is history, these are all actions and events that took place over
              hundreds or a few thousands years ago, they act as a precursor to the Intrigue stage
              and don't need to be very nuanced or detailed.
            </li>
            <li>
              Intrigue is the most recent history, these are all actions and events that have taken
              place in the last few decades or years. These actions and events act as a lead into
              the story of the world and set up the major plots and stories.
            </li>
          </ol>
        </SubSection>

        <SubSection id="natural-disasters" title="Natural Disasters">
          <p>
            Natural Disasters happen during any age and are triggered whenever a player draws an Ace
            card. When this happens, the player who drew the card should decide what happens.
            Examples of natural disasters could be a volcanic eruption, an earthquake, a tsunami, a
            meteor, a plague, a tornado, etc.
          </p>
        </SubSection>

        <StageSection
          id="1.-genesis"
          title="1. Genesis"
          description="The Genesis stage represents the early stage of a world, the main focus of this stage is to create a terrain/landscape for everything else to be in. Players should focus on using their powers during this stage to add features to the map."
          preStage="Before starting this stage, make sure you already have some basic terrain features such as coastlines for your continent(s) and maybe a river, or a mountain or two."
          powers={[
            { id: '(♠)---earth', suit: '♠', name: 'Earth', description: 'This power represents earthly features: mountains, hills, canyons, deserts, cliffs, caves, etc.' },
            { id: '(♥)---water', suit: '♥', name: 'Water', description: 'This power represents watery features: rivers, lakes, swamps, waterfalls, tidal pools, maelstroms, glaciers, etc.' },
            { id: '(♣)---plant', suit: '♣', name: 'Plant', description: 'This power represents the vegetation, flora, and plants: forests, jungles, grasslands, rainforests, marshes, etc.' },
            { id: '(♦)---feature', suit: '♦', name: 'Feature', description: 'This power represents specific features, or elements in the world: weather, climates, unique places, special formations, complex geological elements, for example; geysers, craters, strong winds, currents, salt flats, landmarks, lava flows, natural resources, etc. Things that you would put on a map that aren\'t really represented with the other powers.' },
          ]}
        />

        <StageSection
          id="2.-primal"
          title="2. Primal"
          description="The Primal stage represents the origin of intelligent species and races and what makes them special. The focus is on introducing new species to the world, and developing them. Players will each create a species, and then take turns enhancing those species in preparation for the next stage. Species here refers to a race of sentient beings that will be the basis for the nations and societies for the Civilization and Intrigue stages; Humans, Elves, Dwarves, Orcs, etc."
          preStage="Before starting this stage, each player should create a species, describing them and naming them and deciding where on the map they originated from."
          powers={[
            { id: '(♠)---settlement', suit: '♠', name: 'Settlement', description: 'Enhance the species with a settlement; villages, towns, small cities, etc. (Major Cities, Kingdoms, Empires, and the like are more complex and are only available during the Civilization stage.)' },
            { id: '(♥)---tradition', suit: '♥', name: 'Tradition', description: 'Enhance the species with a tradition; religious, cultural, militaristic, ritualistic, agricultural, rites of passage, etc.' },
            { id: '(♣)---resource', suit: '♣', name: 'Resource', description: 'Enhance the species with a resource; domesticated crops or animals, raw materials (wood, stone, iron, etc), natural resource, etc.' },
            { id: '(♦)---skill', suit: '♦', name: 'Skill', description: 'Enhance the species with a skill; something that they are the greatest at, hunting, sailing, climbing, building, crafting, farming, etc.' },
          ]}
        />

        <StageSection
          id="3.-civilization"
          title="3. Civilization"
          description="The Civilization stage represents the development of species into varied societies and their impact on nature, the landscape, and each other. The focus is on making the different societies more unique, by playing the stage from their perspective. To let the species created during the Primal stage interact with each other and the world around them in interesting ways and diverge and grow as societies. The powers of this stage should be from the perspective of Societies, Civilizations, and Groups. Many of the powers in this stage can overlap in their effects, and that is okay, they are different approaches with different motivations which leads to a deeper world."
          preStage="Before starting this stage, each player should create some societies within the different species which might grow and expand during this stage into kingdoms or empires."
          powers={[
            { id: '(♠)---construction', suit: '♠', name: 'Construction', description: 'The power of construction; the society will complete a significant construction project. Building a new City, Roads and Bridges, A Castle, A University, Terraform the landscape, etc.' },
            { id: '(♥)---enlightenment', suit: '♥', name: 'Enlightenment', description: 'The power of enlightenment; the society will discover or develop technologically, scientifically, socially, culturally, or religiously. Becoming the best at something (mining, farming, boat-making, armor-crafting, architecture, medicine) or becoming paragons of new thinking; governments (feudalism, republic, aristocracy, etc), philosophy (pacifism, militarism, socialism, etc), arts (music, painting, sculptures) or becoming moved by their beliefs to build monuments, spread religion, or adhere to dogmas.' },
            { id: '(♣)---expansion', suit: '♣', name: 'Expansion', description: 'The power of expansion; the society will expand their borders through war, conquest, exploration, population growth, or alliance with other societies. Taking control of land that is owned by others or not at all. Founding new settlements, integrating into old settlements or conquering them. Forming kingdoms and empires.' },
            { id: '(♦)---diplomacy', suit: '♦', name: 'Diplomacy', description: 'The power of diplomacy; the society will work with other societies to trade, learn, grow, or cooperate together or against others. Exchanging goods and ideas for prosperity, making alliances, joining dynasties by marriage, forming kingdoms and empires. Brokering peace, ending wars, negotiating borders.' },
          ]}
        />

        <StageSection
          id="4.-intrigue"
          title="4. Intrigue"
          description="The Intrigue stage is where the players create the very recent history of the world. It represents the late stages of a world, where societies have already developed rich mythologies, where they interact with one another, and discover mysteries. The focus on this stage is enrich the world with connections, friendly or unfriendly and between the world, it's landscape, and its populace. The focus of this stage is to make the world an interesting place for telling stories, by discussing and creating plots, stories, and events that are all tied together, all close together, and all within a few decades of the start of the story."
          preStage="Before this stage, you should make sure to give names to cities, nations, and societies. And deliberate on their aspects that you have developed over the last two stages. Noting the power, influence, armies, government, economy, etc of the different societies in the world."
          powers={[
            { id: '(♠)---conflict', suit: '♠', name: 'Conflict', description: 'The power of conflict; Groups work against each other, wars, battles, zealots purging heretics, cities are destroyed, etc. Conflicts can be specific or general, tactical or strategic, conquest or raid. Conflicts could be internal or between societies.' },
            { id: '(♥)---cooperation', suit: '♥', name: 'Cooperation', description: 'The power of cooperation; Groups work together, trading goods and ideas, helping each other, protecting each other, etc. When cooperating societies can accomplish great things, or bring down great foes, they can be good or bad, fast or slow, ongoing or temporary.' },
            { id: '(♣)---scheme', suit: '♣', name: 'Scheme', description: 'The power of scheming; Groups scheme and plot, spies and informants trade and share information and secrets, kings are assassinated, black markets are formed, secret alliances are made, etc. Anything that happens as part of a complex plot, or plans that are set in motion only to be triggered later, ongoing things in the world. Schemes can be internal to a society or involve multiple societies.' },
            { id: '(♦)---myth', suit: '♦', name: 'Myth', description: 'The power of myth; this lets you add mythical things to your world and the story, they could have been there all along, or only recently arrived. It could be a dragon in a cave, a mysterious lost artifact somewhere in a desert, a lich who lives in a haunted palace near a specific mountain, etc. Myth is a general term which will let you add story elements that are part of the world and interesting for the game or story. These could be plot hooks, quests, or looming dangers in the world.' },
          ]}
        />
      </Section>

      <Section id="glossary-of-terms" title="Glossary of Terms">
        <p className="text-muted-foreground italic">Fill me in?</p>
      </Section>

      <Section id="reference-table" title="Reference Table">
        <div className="overflow-x-auto">
          <table className="min-w-full border-collapse border border-border">
            <thead>
              <tr className="bg-muted">
                <th className="border border-border p-3 text-left"></th>
                <th className="border border-border p-3 text-center">1 - Genesis</th>
                <th className="border border-border p-3 text-center">2 - Primal</th>
                <th className="border border-border p-3 text-center">3 - Civilization</th>
                <th className="border border-border p-3 text-center">4 - Intrigue</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-border p-3 font-semibold">♠</td>
                <td className="border border-border p-3 text-center">Earth</td>
                <td className="border border-border p-3 text-center">Settlement</td>
                <td className="border border-border p-3 text-center">Construction</td>
                <td className="border border-border p-3 text-center">Conflict</td>
              </tr>
              <tr>
                <td className="border border-border p-3 font-semibold">♥</td>
                <td className="border border-border p-3 text-center">Water</td>
                <td className="border border-border p-3 text-center">Tradition</td>
                <td className="border border-border p-3 text-center">Enlightenment</td>
                <td className="border border-border p-3 text-center">Cooperation</td>
              </tr>
              <tr>
                <td className="border border-border p-3 font-semibold">♣</td>
                <td className="border border-border p-3 text-center">Plant</td>
                <td className="border border-border p-3 text-center">Resource</td>
                <td className="border border-border p-3 text-center">Expansion</td>
                <td className="border border-border p-3 text-center">Scheme</td>
              </tr>
              <tr>
                <td className="border border-border p-3 font-semibold">♦</td>
                <td className="border border-border p-3 text-center">Feature</td>
                <td className="border border-border p-3 text-center">Skill</td>
                <td className="border border-border p-3 text-center">Diplomacy</td>
                <td className="border border-border p-3 text-center">Myth</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="mt-4 text-sm text-muted-foreground">
          <strong>Aces:</strong> Natural Disaster, <strong>Face Cards:</strong> Fantastical Power,{' '}
          <strong>Joker:</strong> Any Fantastical Power
        </p>
      </Section>

      <Section id="acknowledgements" title="Acknowledgements">
        <SubSection id="the-author" title="The Author">
          <p>
            I am Inbar Rose. <a href="mailto:inbarrose@gmail.com" className="text-primary hover:underline">inbarrose@gmail.com</a>. I love roleplaying games and World Building. And I made this so that I could have fun with my friends doing what I love.
          </p>
        </SubSection>

        <SubSection id="inspiration" title="Inspiration">
          <p>
            World Building was inspired by a wonderful system contained in a single document called
            "Dawn of Worlds" (First Edition, July 2005, © N. Bob Pesall, Esq. Attorney At Law,
            Dickinson, ND). This is a total re-thinking of that work, but the ideas came because I
            wanted a better way to do what I did in that game.
          </p>
        </SubSection>

        <SubSection id="thanks" title="Thanks">
          <p>Thanks to Stav Geffen for inspiring me to use Cards for this game. And for helping me focus on what's important.</p>
          <p>Thanks to Golan Gross for being an amazing artist during my first ever attempt at world building, and through his art making me realize how awesome this can be.</p>
          <p>Thanks to Alon Tsang for dropping everything at the last minute to keep us playing, and keep us excited.</p>
        </SubSection>
      </Section>
    </div>
  )
}

interface SectionProps {
  id: string
  title: string
  children: React.ReactNode
}

function Section({ id, title, children }: SectionProps) {
  return (
    <section id={id} className="scroll-mt-8">
      <h2 className="text-3xl font-bold mb-4 pt-8 border-t border-border first:border-t-0 first:pt-0">
        {title}
      </h2>
      <div className="space-y-4">{children}</div>
    </section>
  )
}

interface SubSectionProps {
  id: string
  title: string
  children: React.ReactNode
}

function SubSection({ id, title, children }: SubSectionProps) {
  return (
    <section id={id} className="scroll-mt-8">
      <h3 className="text-2xl font-semibold mb-3 mt-6">{title}</h3>
      <div className="space-y-4">{children}</div>
    </section>
  )
}

interface Power {
  id: string
  suit: string
  name: string
  description: string
}

interface StageSectionProps {
  id: string
  title: string
  description: string
  preStage: string
  powers: Power[]
}

function StageSection({ id, title, description, preStage, powers }: StageSectionProps) {
  return (
    <section id={id} className="scroll-mt-8">
      <h3 className="text-2xl font-semibold mb-3 mt-6">{title}</h3>
      <p className="mb-4">{description}</p>
      <div className="bg-muted/50 p-4 rounded-lg mb-4">
        <p className="font-semibold mb-2">Pre-{title}:</p>
        <p className="text-sm">{preStage}</p>
      </div>
      <div className="space-y-4">
        {powers.map((power) => (
          <div key={power.id} id={power.id} className="scroll-mt-8 border-l-4 border-primary pl-4">
            <h4 className="text-xl font-semibold mb-2">
              ({power.suit}) - {power.name}
            </h4>
            <p>{power.description}</p>
          </div>
        ))}
      </div>
    </section>
  )
}
