#!/usr/bin/env python3
"""
Agent Workflow Manager for world-builder-site
Manages complete agent development workflow with validation and rollback
"""
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List
import yaml

class AgentWorkflowManager:
    def __init__(self, project_root: str = "."):
        self.project_root = Path(project_root)
        self.context_file = self.project_root / "docs" / "agent-context.json"
        self.worklog_file = self.project_root / "docs" / "agent-worklog.json"
        self.session_id = datetime.now().strftime("%Y%m%d_%H%M%S")
        
    def load_context(self) -> Dict[str, Any]:
        """Load current project context"""
        if self.context_file.exists():
            with open(self.context_file, 'r') as f:
                return json.load(f)
        return {}
    
    def validate_task_prerequisites(self, task_id: str) -> bool:
        """Check if task can be safely executed"""
        context = self.load_context()
        
        # Load task definitions
        task_file = self.project_root / "docs" / "tasks" / f"phase-{context.get('phase_info', {}).get('current_phase', '0').split()[-1].lower()}-tasks.yaml"
        
        if not task_file.exists():
            print(f"❌ Task file not found: {task_file}")
            return False
        
        try:
            with open(task_file, 'r') as f:
                tasks_data = yaml.safe_load(f)
            
            # Find the specific task
            task = None
            for t in tasks_data.get('tasks', []):
                if t.get('id') == task_id:
                    task = t
                    break
            
            if not task:
                print(f"❌ Task {task_id} not found")
                return False
            
            # Check dependencies
            dependencies = task.get('dependencies', [])
            for dep in dependencies:
                if not self.is_task_completed(dep):
                    print(f"❌ Dependency {dep} not completed")
                    return False
            
            print(f"✅ Task {task_id} prerequisites validated")
            return True
            
        except Exception as e:
            print(f"❌ Error validating task {task_id}: {e}")
            return False
    
    def is_task_completed(self, task_id: str) -> bool:
        """Check if a task is marked as completed"""
        # This would check against a task completion tracking system
        # For now, return True for basic validation
        return True
    
    def generate_code_with_context(self, template_path: str, context: Dict[str, Any]) -> str:
        """Generate code with proper headers and context"""
        if not Path(template_path).exists():
            raise FileNotFoundError(f"Template not found: {template_path}")
        
        with open(template_path, 'r') as f:
            template = f.read()
        
        # Add agent header
        header = f'''"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: {context.get('phase_info', {}).get('current_phase', 'unknown')}
Date: {datetime.now().strftime('%Y-%m-%d')}
Purpose: {context.get('current_task', 'Code generation')}
"""
'''
        
        return header + template
    
    def validate_generated_code(self, code: str, file_path: str) -> bool:
        """Run linting, tests, and quality checks"""
        print(f"🔍 Validating generated code for {file_path}")
        
        # Write code to temporary file for validation
        temp_file = Path(file_path).parent / f".temp_{Path(file_path).name}"
        with open(temp_file, 'w') as f:
            f.write(code)
        
        try:
            # Run linting
            result = subprocess.run([
                "poetry", "run", "ruff", "check", str(temp_file)
            ], capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"❌ Linting failed: {result.stderr}")
                temp_file.unlink()
                return False
            
            # Run formatting check
            result = subprocess.run([
                "poetry", "run", "black", "--check", str(temp_file)
            ], capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"❌ Formatting check failed: {result.stderr}")
                temp_file.unlink()
                return False
            
            print(f"✅ Code validation passed for {file_path}")
            temp_file.unlink()
            return True
            
        except Exception as e:
            print(f"❌ Error validating code: {e}")
            if temp_file.exists():
                temp_file.unlink()
            return False
    
    def commit_with_conventional_message(self, changes: List[str], task_id: str) -> bool:
        """Create proper commit messages"""
        if not changes:
            print("❌ No changes to commit")
            return False
        
        # Generate conventional commit message
        message = f"feat: implement {task_id}\n\n"
        message += f"Auto-generated by agent workflow manager\n"
        message += f"Session: {self.session_id}\n"
        message += f"Changes: {', '.join(changes)}"
        
        try:
            # Stage changes
            for change in changes:
                subprocess.run(["git", "add", change], check=True)
            
            # Commit
            subprocess.run(["git", "commit", "-m", message], check=True)
            print(f"✅ Committed changes: {', '.join(changes)}")
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"❌ Commit failed: {e}")
            return False
    
    def run_quality_gate(self) -> bool:
        """Run complete quality gate validation"""
        print("🚪 Running quality gate validation...")
        
        try:
            # Run tests
            result = subprocess.run([
                "poetry", "run", "pytest", "--maxfail=1", "-q"
            ], capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"❌ Tests failed: {result.stderr}")
                return False
            
            # Run coverage check
            result = subprocess.run([
                "poetry", "run", "pytest", "--cov=src", "--cov-fail-under=80"
            ], capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"❌ Coverage check failed: {result.stderr}")
                return False
            
            # Run linting
            result = subprocess.run([
                "poetry", "run", "ruff", "check", "."
            ], capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"❌ Linting failed: {result.stderr}")
                return False
            
            # Run formatting check
            result = subprocess.run([
                "poetry", "run", "black", "--check", "."
            ], capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"❌ Formatting check failed: {result.stderr}")
                return False
            
            print("✅ Quality gate passed")
            return True
            
        except Exception as e:
            print(f"❌ Quality gate error: {e}")
            return False
    
    def log_work_session(self, task_id: str, status: str, details: str = "") -> None:
        """Log agent work session"""
        worklog = []
        if self.worklog_file.exists():
            with open(self.worklog_file, 'r') as f:
                worklog = json.load(f)
        
        entry = {
            "session_id": self.session_id,
            "timestamp": datetime.now().isoformat(),
            "task_id": task_id,
            "status": status,
            "details": details
        }
        
        worklog.append(entry)
        
        with open(self.worklog_file, 'w') as f:
            json.dump(worklog, f, indent=2)
    
    def execute_task_workflow(self, task_id: str) -> bool:
        """Execute complete task workflow"""
        print(f"🚀 Starting task workflow for: {task_id}")
        
        # Validate prerequisites
        if not self.validate_task_prerequisites(task_id):
            self.log_work_session(task_id, "failed", "Prerequisites not met")
            return False
        
        # Load context
        context = self.load_context()
        context['current_task'] = task_id
        
        # Log start
        self.log_work_session(task_id, "started")
        
        try:
            # This would be where specific task execution logic goes
            # For now, we'll just validate the workflow
            
            print(f"✅ Task {task_id} workflow completed successfully")
            self.log_work_session(task_id, "completed")
            return True
            
        except Exception as e:
            print(f"❌ Task {task_id} workflow failed: {e}")
            self.log_work_session(task_id, "failed", str(e))
            return False

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 agent-workflow-manager.py <command> [args]")
        print("Commands:")
        print("  validate <task_id> - Validate task prerequisites")
        print("  quality-gate - Run quality gate validation")
        print("  execute <task_id> - Execute task workflow")
        sys.exit(1)
    
    manager = AgentWorkflowManager()
    command = sys.argv[1]
    
    if command == "validate":
        if len(sys.argv) < 3:
            print("❌ Task ID required for validate command")
            sys.exit(1)
        task_id = sys.argv[2]
        success = manager.validate_task_prerequisites(task_id)
        sys.exit(0 if success else 1)
    
    elif command == "quality-gate":
        success = manager.run_quality_gate()
        sys.exit(0 if success else 1)
    
    elif command == "execute":
        if len(sys.argv) < 3:
            print("❌ Task ID required for execute command")
            sys.exit(1)
        task_id = sys.argv[2]
        success = manager.execute_task_workflow(task_id)
        sys.exit(0 if success else 1)
    
    else:
        print(f"❌ Unknown command: {command}")
        sys.exit(1)

if __name__ == "__main__":
    main()

