@echo off
REM Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
REM Phase: Phase 0 - Foundation
REM Date: 2025-01-27
REM Purpose: Windows development environment setup

echo 🔧 world-builder-site: Windows Development Setup
echo ================================================
echo.

REM Check if we're in the right directory
if not exist "pyproject.toml" (
    echo ❌ Not in project root directory. Please run from project root.
    pause
    exit /b 1
)

echo 📋 Checking prerequisites...

REM Check Python version
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ Python not found. Please install Python 3.12+ from https://python.org
    pause
    exit /b 1
)

REM Get Python version
for /f "tokens=2" %%i in ('python --version 2^>^&1') do set PYTHON_VERSION=%%i
echo ✅ Python %PYTHON_VERSION% detected

REM Check Poetry
poetry --version >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ Poetry not found. Installing Poetry...
    powershell -Command "(Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -"
    
    REM Add Poetry to PATH
    set PATH=%USERPROFILE%\.local\bin;%PATH%
    
    poetry --version >nul 2>&1
    if %errorlevel% neq 0 (
        echo ❌ Poetry installation failed. Please install manually:
        echo curl -sSL https://install.python-poetry.org | python -
        pause
        exit /b 1
    )
)

echo ✅ Poetry available: 
poetry --version

REM Install dependencies
echo.
echo 📦 Installing project dependencies...
poetry install
if %errorlevel% neq 0 (
    echo ❌ Dependency installation failed
    pause
    exit /b 1
)

echo ✅ Dependencies installed successfully

REM Create .env file if it doesn't exist
if not exist ".env" (
    echo.
    echo 🔐 Creating .env file template...
    (
        echo # Supabase Configuration
        echo SUPABASE_URL=your-supabase-url-here
        echo SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-here
        echo SUPABASE_ANON_KEY=your-anon-key-here
        echo.
        echo # Vercel Configuration
        echo VERCEL_TOKEN=your-vercel-token-here
        echo.
        echo # Development Settings
        echo DEBUG=true
        echo LOG_LEVEL=info
        echo DATABASE_URL=sqlite:///./world_builder.db
        echo DATABASE_ECHO=false
    ) > .env
    echo ✅ .env file created. Please update with your actual values.
) else (
    echo ✅ .env file already exists
)

REM Create GitHub secrets documentation
if not exist ".github\secrets.md" (
    echo.
    echo 📝 Creating GitHub secrets documentation...
    if not exist ".github" mkdir .github
    (
        echo # GitHub Secrets Configuration
        echo.
        echo ## Required Secrets
        echo.
        echo Add these secrets to your GitHub repository settings:
        echo.
        echo ### Supabase
        echo - `SUPABASE_URL`: Your Supabase project URL
        echo - `SUPABASE_SERVICE_ROLE_KEY`: Service role key for database access
        echo - `SUPABASE_ANON_KEY`: Anonymous key for client access
        echo.
        echo ### Vercel
        echo - `VERCEL_TOKEN`: Vercel API token for deployment
        echo.
        echo ## How to Add Secrets
        echo.
        echo 1. Go to your GitHub repository
        echo 2. Click Settings → Secrets and variables → Actions
        echo 3. Click "New repository secret"
        echo 4. Add each secret with the exact name above
        echo.
        echo ## Local Development
        echo.
        echo Copy `.env.example` to `.env` and fill in your values for local development.
    ) > .github\secrets.md
    echo ✅ GitHub secrets documentation created
)

REM Validate installation
echo.
echo 🔍 Validating installation...

REM Check if FastAPI can be imported
poetry run python -c "import fastapi; print('FastAPI version:', fastapi.__version__)" 2>nul
if %errorlevel% neq 0 (
    echo ❌ FastAPI not available
    pause
    exit /b 1
)
echo ✅ FastAPI available

REM Check if SQLModel can be imported
poetry run python -c "import sqlmodel; print('SQLModel available')" 2>nul
if %errorlevel% neq 0 (
    echo ❌ SQLModel not available
    pause
    exit /b 1
)
echo ✅ SQLModel available

REM Check if pytest can be imported
poetry run python -c "import pytest; print('Pytest available')" 2>nul
if %errorlevel% neq 0 (
    echo ❌ Pytest not available
    pause
    exit /b 1
)
echo ✅ Pytest available

REM Run basic linting check
echo.
echo 🔍 Running basic validation...

poetry run ruff check . --no-fix 2>nul
if %errorlevel% neq 0 (
    echo ⚠️  Ruff linting issues found (this is expected for initial setup)
) else (
    echo ✅ Ruff linting passed
)

poetry run black --check . 2>nul
if %errorlevel% neq 0 (
    echo ⚠️  Black formatting issues found (this is expected for initial setup)
) else (
    echo ✅ Black formatting check passed
)

REM Create basic FastAPI app if it doesn't exist
if not exist "src\app\main.py" (
    echo.
    echo 🚀 Creating basic FastAPI application...
    if not exist "src\app" mkdir src\app
    (
        echo """Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Basic FastAPI application setup
"""
        echo from fastapi import FastAPI
        echo from fastapi.middleware.cors import CORSMiddleware
        echo.
        echo app = FastAPI^(
        echo     title="World Builder Site API",
        echo     description="Backend API for collaborative world-building application",
        echo     version="0.1.0"
        echo ^)
        echo.
        echo # Add CORS middleware
        echo app.add_middleware^(
        echo     CORSMiddleware,
        echo     allow_origins=["*"],  # Configure appropriately for production
        echo     allow_credentials=True,
        echo     allow_methods=["*"],
        echo     allow_headers=["*"],
        echo ^)
        echo.
        echo @app.get^("/"^)
        echo async def root^(^):
        echo     """Root endpoint"""
        echo     return {"message": "World Builder Site API", "version": "0.1.0"}
        echo.
        echo @app.get^("/health"^)
        echo async def health_check^(^):
        echo     """Health check endpoint"""
        echo     return {"status": "healthy", "timestamp": "2025-01-27T00:00:00Z"}
        echo.
        echo if __name__ == "__main__":
        echo     import uvicorn
        echo     uvicorn.run^(app, host="0.0.0.0", port=8000^)
    ) > src\app\main.py
    echo ✅ Basic FastAPI application created
)

echo.
echo 🎉 Development environment setup complete!
echo.
echo 📋 Next Steps:
echo 1. Update .env file with your actual Supabase and Vercel credentials
echo 2. Add GitHub secrets as documented in .github\secrets.md
echo 3. Run 'poetry run uvicorn src.app.main:app --reload' to start backend
echo 4. Run 'cd frontend ^&^& npm install ^&^& npm run dev' to start frontend
echo.
echo 🛠️  Available Commands:
echo   poetry run uvicorn src.app.main:app --reload  # Start backend
echo   poetry run pytest                            # Run tests
echo   poetry run ruff check .                      # Run linting
echo   poetry run black .                          # Format code
echo   cd frontend ^&^& npm run dev                 # Start frontend
echo.
pause

