#!/usr/bin/env bash
set -e
echo "Setting up development environment (guide)"
echo "-----------------------------------------"
echo "1) Install Python 3.12+ and Poetry"
echo "   https://python.org https://python-poetry.org"
echo ""
echo "2) Install project dependencies:"
echo "   poetry install"
echo ""
echo "3) Create .env file with these values (example):"
echo "   SUPABASE_URL=your-db-url"
echo "   SUPABASE_SERVICE_ROLE_KEY=supersecret"
echo "   VERCEL_TOKEN=token"
echo ""
echo "4) Initialize DB (local) or configure Supabase..."
echo "   alembic upgrade head  # after implementing migrations"
echo ""
echo "5) Start backend (dev):"
echo "   poetry run uvicorn src.app.main:app --reload"
echo ""
echo "6) Start frontend (dev):"
echo "   cd frontend && npm install && npm run dev"
echo ""
echo "This script is a guide. Implement local dev automation as needed."
