#!/usr/bin/env bash
# Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
# Phase: Phase 0 - Foundation
# Date: 2025-01-27
# Purpose: Start development servers for both backend and frontend

echo "🚀 Starting World Builder Site Development Servers"
echo "=================================================="
echo ""

# Check if we're in the right directory
if [ ! -f "pyproject.toml" ]; then
    echo "❌ Not in project root directory. Please run from project root."
    exit 1
fi

# Function to start backend
start_backend() {
    echo "🐍 Starting FastAPI backend on http://localhost:8000"
    echo "📖 API docs available at http://localhost:8000/docs"
    echo ""
    
    poetry run uvicorn src.app.main:app --reload --host 0.0.0.0 --port 8000
}

# Function to start frontend
start_frontend() {
    echo "⚛️  Starting React frontend on http://localhost:3000"
    echo ""
    
    cd frontend
    npm run dev
}

# Function to start both
start_both() {
    echo "🔄 Starting both backend and frontend..."
    echo ""
    
    # Start backend in background
    poetry run uvicorn src.app.main:app --reload --host 0.0.0.0 --port 8000 &
    BACKEND_PID=$!
    
    # Wait a moment for backend to start
    sleep 3
    
    # Start frontend
    cd frontend
    npm run dev &
    FRONTEND_PID=$!
    
    echo "✅ Both servers started!"
    echo "   Backend: http://localhost:8000"
    echo "   Frontend: http://localhost:3000"
    echo ""
    echo "Press Ctrl+C to stop both servers"
    
    # Wait for interrupt
    trap "kill $BACKEND_PID $FRONTEND_PID; exit" INT
    wait
}

# Parse command line arguments
case "${1:-both}" in
    "backend")
        start_backend
        ;;
    "frontend")
        start_frontend
        ;;
    "both")
        start_both
        ;;
    "help")
        echo "Usage: $0 [backend|frontend|both|help]"
        echo ""
        echo "Commands:"
        echo "  backend  - Start only the FastAPI backend"
        echo "  frontend - Start only the React frontend"
        echo "  both     - Start both servers (default)"
        echo "  help     - Show this help message"
        echo ""
        echo "Examples:"
        echo "  $0              # Start both servers"
        echo "  $0 backend      # Start only backend"
        echo "  $0 frontend     # Start only frontend"
        ;;
    *)
        echo "❌ Unknown command: $1"
        echo "Run '$0 help' for usage information"
        exit 1
        ;;
esac

