@echo off
REM Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
REM Phase: Phase 0 - Foundation
REM Date: 2025-01-27
REM Purpose: Start development servers for Windows

echo 🚀 Starting World Builder Site Development Servers
echo ==================================================
echo.

REM Check if we're in the right directory
if not exist "pyproject.toml" (
    echo ❌ Not in project root directory. Please run from project root.
    pause
    exit /b 1
)

REM Parse command line arguments
set COMMAND=%1
if "%COMMAND%"=="" set COMMAND=both

if "%COMMAND%"=="backend" goto :start_backend
if "%COMMAND%"=="frontend" goto :start_frontend
if "%COMMAND%"=="both" goto :start_both
if "%COMMAND%"=="help" goto :show_help
goto :unknown_command

:start_backend
echo 🐍 Starting FastAPI backend on http://localhost:8000
echo 📖 API docs available at http://localhost:8000/docs
echo.
poetry run uvicorn src.app.main:app --reload --host 0.0.0.0 --port 8000
goto :end

:start_frontend
echo ⚛️  Starting React frontend on http://localhost:3000
echo.
cd frontend
npm run dev
goto :end

:start_both
echo 🔄 Starting both backend and frontend...
echo.

REM Start backend in background
start "Backend Server" cmd /c "poetry run uvicorn src.app.main:app --reload --host 0.0.0.0 --port 8000"

REM Wait a moment for backend to start
timeout /t 3 /nobreak >nul

REM Start frontend
cd frontend
start "Frontend Server" cmd /c "npm run dev"

echo ✅ Both servers started!
echo    Backend: http://localhost:8000
echo    Frontend: http://localhost:3000
echo.
echo Press any key to stop both servers...
pause >nul

REM Kill both processes
taskkill /f /im python.exe >nul 2>&1
taskkill /f /im node.exe >nul 2>&1
goto :end

:show_help
echo Usage: %0 [backend^|frontend^|both^|help]
echo.
echo Commands:
echo   backend  - Start only the FastAPI backend
echo   frontend - Start only the React frontend
echo   both     - Start both servers (default)
echo   help     - Show this help message
echo.
echo Examples:
echo   %0              # Start both servers
echo   %0 backend      # Start only backend
echo   %0 frontend     # Start only frontend
goto :end

:unknown_command
echo ❌ Unknown command: %COMMAND%
echo Run '%0 help' for usage information
exit /b 1

:end

