"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Entity model for world objects on the map
"""
from sqlmodel import SQLModel, Field, Relationship
from typing import Optional
from datetime import datetime
from uuid import UUID, uuid4
from pydantic import BaseModel

class EntityBase(SQLModel):
    """Base entity model"""
    name: str = Field(max_length=100)
    entity_type: str = Field(max_length=50, default="landmark")
    x: int = Field(ge=0, le=19)  # Grid width: 20
    y: int = Field(ge=0, le=11)  # Grid height: 12
    description: Optional[str] = Field(default=None, max_length=500)
    size: int = Field(default=1, ge=1, le=5)  # Entity size in grid units

class Entity(EntityBase, table=True):
    """Entity model for database"""
    __tablename__ = "entities"
    
    id: Optional[UUID] = Field(default_factory=uuid4, primary_key=True)
    session_id: UUID = Field(foreign_key="sessions.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = Field(default=None)
    
    # Relationships
    session: "GameSession" = Relationship(back_populates="entities")
    
    class Config:
        arbitrary_types_allowed = True

class EntityCreate(BaseModel):
    """Request model for entity creation"""
    name: str = Field(max_length=100)
    entity_type: str = Field(max_length=50, default="landmark")
    x: int = Field(ge=0, le=19)
    y: int = Field(ge=0, le=11)
    description: Optional[str] = Field(default=None, max_length=500)
    size: int = Field(default=1, ge=1, le=5)

class EntityResponse(BaseModel):
    """Response model for entity data"""
    id: UUID
    session_id: UUID
    name: str
    entity_type: str
    x: int
    y: int
    description: Optional[str] = None
    size: int
    created_at: datetime
    updated_at: Optional[datetime] = None
    
    class Config:
        from_attributes = True

class EntityUpdate(BaseModel):
    """Request model for entity updates"""
    name: Optional[str] = Field(max_length=100, default=None)
    entity_type: Optional[str] = Field(max_length=50, default=None)
    x: Optional[int] = Field(ge=0, le=19, default=None)
    y: Optional[int] = Field(ge=0, le=11, default=None)
    description: Optional[str] = Field(max_length=500, default=None)
    size: Optional[int] = Field(ge=1, le=5, default=None)

