"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Game session model for managing world-building sessions
"""
from sqlmodel import SQLModel, Field, Relationship
from typing import Optional, List
from datetime import datetime
from uuid import UUID, uuid4
from pydantic import BaseModel

class SessionBase(SQLModel):
    """Base session model with common fields"""
    name: str = Field(max_length=100)
    description: Optional[str] = Field(default=None, max_length=500)
    is_active: bool = Field(default=True)
    current_stage: str = Field(default="foundation")
    move_count: int = Field(default=0)
    current_year: int = Field(default=0)

class GameSession(SessionBase, table=True):
    """Game session model for database"""
    __tablename__ = "sessions"
    
    id: Optional[UUID] = Field(default_factory=uuid4, primary_key=True)
    user_id: Optional[UUID] = Field(default=None, foreign_key="users.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = Field(default=None)
    
    # Relationships
    user: Optional["User"] = Relationship(back_populates="sessions")
    timeline_events: List["TimelineEvent"] = Relationship(back_populates="session")
    tiles: List["Tile"] = Relationship(back_populates="session")
    entities: List["Entity"] = Relationship(back_populates="session")
    
    class Config:
        arbitrary_types_allowed = True

class SessionCreate(BaseModel):
    """Request model for session creation"""
    name: str = Field(max_length=100)
    description: Optional[str] = Field(default=None, max_length=500)
    current_stage: str = Field(default="foundation")

class SessionResponse(BaseModel):
    """Response model for session data"""
    id: UUID
    name: str
    description: Optional[str] = None
    is_active: bool
    current_stage: str
    move_count: int
    current_year: int
    created_at: datetime
    updated_at: Optional[datetime] = None
    
    class Config:
        from_attributes = True

class SessionUpdate(BaseModel):
    """Request model for session updates"""
    name: Optional[str] = Field(max_length=100, default=None)
    description: Optional[str] = Field(max_length=500, default=None)
    is_active: Optional[bool] = None
    current_stage: Optional[str] = None
    move_count: Optional[int] = None
    current_year: Optional[int] = None

class SessionState(BaseModel):
    """Complete session state for export/import"""
    session: SessionResponse
    timeline: List["TimelineEventResponse"] = []
    tiles: List["TileResponse"] = []
    entities: List["EntityResponse"] = []

