"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Tile model for map grid system
"""
from sqlmodel import SQLModel, Field, Relationship
from typing import Optional, List, TYPE_CHECKING
from datetime import datetime
from uuid import UUID, uuid4
from pydantic import BaseModel

if TYPE_CHECKING:
    from src.models.session import GameSession
    from src.models.entity import EntityResponse

class TileBase(SQLModel):
    """Base tile model"""
    x: int = Field(ge=0, le=19)  # Grid width: 20
    y: int = Field(ge=0, le=11)  # Grid height: 12
    tile_type: str = Field(max_length=50, default="empty")
    notes: Optional[str] = Field(default=None, max_length=500)

class Tile(TileBase, table=True):
    """Tile model for database"""
    __tablename__ = "tiles"
    
    id: Optional[UUID] = Field(default_factory=uuid4, primary_key=True)
    session_id: UUID = Field(foreign_key="sessions.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = Field(default=None)
    
    # Relationships
    session: "GameSession" = Relationship(back_populates="tiles")
    
    class Config:
        arbitrary_types_allowed = True

class TileCreate(BaseModel):
    """Request model for tile creation"""
    x: int = Field(ge=0, le=19)
    y: int = Field(ge=0, le=11)
    tile_type: str = Field(max_length=50, default="empty")
    notes: Optional[str] = Field(default=None, max_length=500)

class TileResponse(BaseModel):
    """Response model for tile data"""
    id: UUID
    session_id: UUID
    x: int
    y: int
    tile_type: str
    notes: Optional[str] = None
    created_at: datetime
    updated_at: Optional[datetime] = None
    
    class Config:
        from_attributes = True

class TileUpdate(BaseModel):
    """Request model for tile updates"""
    tile_type: Optional[str] = Field(max_length=50, default=None)
    notes: Optional[str] = Field(max_length=500, default=None)

class MapState(BaseModel):
    """Complete map state"""
    tiles: list[TileResponse] = []
    entities: list["EntityResponse"] = []
    width: int = 20
    height: int = 12

