"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Timeline event model for tracking world history
"""
from sqlmodel import SQLModel, Field, Relationship
from typing import Optional, TYPE_CHECKING
from datetime import datetime
from uuid import UUID, uuid4
from pydantic import BaseModel

if TYPE_CHECKING:
    from src.models.session import GameSession

class TimelineEventBase(SQLModel):
    """Base timeline event model"""
    move_id: int = Field(ge=1)
    year: int = Field(ge=0)
    description: str = Field(max_length=1000)
    card_id: Optional[str] = Field(default=None, max_length=50)
    event_type: str = Field(default="card_draw", max_length=50)

class TimelineEvent(TimelineEventBase, table=True):
    """Timeline event model for database"""
    __tablename__ = "timeline_events"
    
    id: Optional[UUID] = Field(default_factory=uuid4, primary_key=True)
    session_id: UUID = Field(foreign_key="sessions.id")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Relationships
    session: "GameSession" = Relationship(back_populates="timeline_events")
    
    class Config:
        arbitrary_types_allowed = True

class TimelineEventCreate(BaseModel):
    """Request model for timeline event creation"""
    move_id: int = Field(ge=1)
    year: int = Field(ge=0)
    description: str = Field(max_length=1000)
    card_id: Optional[str] = Field(default=None, max_length=50)
    event_type: str = Field(default="card_draw", max_length=50)

class TimelineEventResponse(BaseModel):
    """Response model for timeline event data"""
    id: UUID
    session_id: UUID
    move_id: int
    year: int
    description: str
    card_id: Optional[str] = None
    event_type: str
    created_at: datetime
    
    class Config:
        from_attributes = True

class TimelineEventUpdate(BaseModel):
    """Request model for timeline event updates"""
    description: Optional[str] = Field(max_length=1000, default=None)
    event_type: Optional[str] = Field(max_length=50, default=None)

