"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: User model for authentication and user management
"""
from sqlmodel import SQLModel, Field, Relationship
from typing import Optional, List
from datetime import datetime
from uuid import UUID, uuid4
from pydantic import BaseModel, EmailStr

class UserBase(SQLModel):
    """Base user model with common fields"""
    username: str = Field(max_length=50, unique=True, index=True)
    email: str = Field(unique=True, index=True)  # Use str instead of EmailStr for SQLModel
    is_active: bool = Field(default=True)
    is_verified: bool = Field(default=False)

class User(UserBase, table=True):
    """User model for database"""
    __tablename__ = "users"
    
    id: Optional[UUID] = Field(default_factory=uuid4, primary_key=True)
    hashed_password: str = Field(max_length=255)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = Field(default=None)
    last_login: Optional[datetime] = Field(default=None)
    
    # Relationships
    sessions: List["GameSession"] = Relationship(back_populates="user")
    
    class Config:
        arbitrary_types_allowed = True

class UserCreate(BaseModel):
    """Request model for user creation"""
    username: str = Field(max_length=50)
    email: EmailStr  # Keep EmailStr for validation in Pydantic models
    password: str = Field(min_length=8)

class UserLogin(BaseModel):
    """Request model for user login"""
    email: EmailStr
    password: str

class UserResponse(BaseModel):
    """Response model for user data"""
    id: UUID
    username: str
    email: str
    is_active: bool
    is_verified: bool
    created_at: datetime
    last_login: Optional[datetime] = None
    
    class Config:
        from_attributes = True

class UserUpdate(BaseModel):
    """Request model for user updates"""
    username: Optional[str] = Field(max_length=50, default=None)
    email: Optional[EmailStr] = None
    is_active: Optional[bool] = None
