"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-10-15
Purpose: Configuration management and environment setup
"""
from pathlib import Path
from typing import Optional
import yaml
import os
from pydantic import BaseModel, Field

class DatabaseConfig(BaseModel):
    url: str
    echo: bool = False
    pool_size: int = Field(default=5, gt=0)
    max_overflow: int = Field(default=10, ge=0)
    ssl_mode: Optional[str] = None

class APIConfig(BaseModel):
    title: str
    version: str
    docs_url: Optional[str] = "/docs"
    redoc_url: Optional[str] = "/redoc"
    cors_origins: list[str]

class AuthConfig(BaseModel):
    jwt_secret: str
    jwt_algorithm: str = "HS256"
    jwt_expiration_hours: int = Field(default=24, gt=0)
    password_min_length: int = Field(default=8, ge=8)

class SupabaseConfig(BaseModel):
    url: str
    service_role_key: str
    anon_key: str

class GameConfig(BaseModel):
    default_grid_width: int = Field(default=20, gt=0)
    default_grid_height: int = Field(default=12, gt=0)
    max_moves_per_session: int = Field(default=1000, gt=0)
    rules_version: str

class RateLimitingConfig(BaseModel):
    enabled: bool = True
    requests_per_minute: int = Field(default=60, gt=0)
    burst_limit: int = Field(default=100, gt=0)

class SecurityConfig(BaseModel):
    enable_csrf: bool = True
    enable_cors: bool = True
    trusted_hosts: list[str] = Field(default_factory=list)

class AppConfig(BaseModel):
    environment: str
    debug: bool = False
    log_level: str = "info"
    database: DatabaseConfig
    api: APIConfig
    auth: AuthConfig
    supabase: SupabaseConfig
    game: GameConfig
    rate_limiting: RateLimitingConfig
    security: Optional[SecurityConfig] = None

def load_config() -> AppConfig:
    """Load configuration based on environment"""
    env = os.getenv("APP_ENV", "development")
    config_dir = Path(__file__).parent.parent / "config" / "environments"
    config_file = config_dir / f"{env}.yaml"
    
    if not config_file.exists():
        raise FileNotFoundError(f"Configuration file not found: {config_file}")
    
    with open(config_file) as f:
        config_data = yaml.safe_load(f)
    
    # Replace environment variables in config
    def replace_env_vars(data):
        if isinstance(data, dict):
            return {k: replace_env_vars(v) for k, v in data.items()}
        elif isinstance(data, list):
            return [replace_env_vars(v) for v in data]
        elif isinstance(data, str) and data.startswith("${") and data.endswith("}"):
            env_var = data[2:-1]
            return os.getenv(env_var, "")
        return data
    
    config_data = replace_env_vars(config_data)
    return AppConfig(**config_data)