"""
Auto-generated by agent under LLM_OPERATING_GUIDE v2.0.
Phase: Phase 0 - Foundation
Date: 2025-01-27
Purpose: Database configuration and session management
"""
from sqlmodel import SQLModel, create_engine, Session
import os
from contextlib import asynccontextmanager

# Database URL configuration
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./world_builder.db")

# Create engine
engine = create_engine(
    DATABASE_URL,
    echo=os.getenv("DATABASE_ECHO", "false").lower() == "true",
    connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {}
)

def get_db():
    """Get database session"""
    with Session(engine) as session:
        yield session

def create_tables():
    """Create all database tables"""
    SQLModel.metadata.create_all(engine)

def drop_tables():
    """Drop all database tables"""
    SQLModel.metadata.drop_all(engine)

@asynccontextmanager
async def get_db_session():
    """Get database session as context manager"""
    session = Session(engine)
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()

